CREATE TABLE `speaker_profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speaker_id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NULL,
  `org` VARCHAR(191) NULL,
  `country` VARCHAR(191) NULL,
  `region` VARCHAR(191) NULL,
  `city` VARCHAR(191) NULL,
  `photo_url` VARCHAR(191) NULL,
  `bio` TEXT NULL,
  `profile_type` VARCHAR(191) NULL,
  `participation_model` VARCHAR(191) NOT NULL DEFAULT 'unknown',
  `lang_fr` BOOLEAN NOT NULL DEFAULT false,
  `lang_en` BOOLEAN NOT NULL DEFAULT false,
  `lang_other` VARCHAR(191) NULL,
  `topic_main` VARCHAR(191) NULL,
  `topics_secondary` JSON NOT NULL DEFAULT ('[]'),
  `keywords` TEXT NULL,
  `tech_level` VARCHAR(191) NULL,
  `certifications` TEXT NULL,
  `linkedin` VARCHAR(191) NULL,
  `twitter` VARCHAR(191) NULL,
  `github` VARCHAR(191) NULL,
  `scholar` VARCHAR(191) NULL,
  `website` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `conferences_past` TEXT NULL,
  `videos_urls` TEXT NULL,
  `publications` TEXT NULL,
  `p1` INT NOT NULL DEFAULT 0,
  `p2` INT NOT NULL DEFAULT 0,
  `p3` INT NOT NULL DEFAULT 0,
  `p4` INT NOT NULL DEFAULT 0,
  `p5` INT NOT NULL DEFAULT 0,
  `p6` INT NOT NULL DEFAULT 0,
  `ip_score` INT NOT NULL DEFAULT 0,
  `tier` VARCHAR(191) NOT NULL DEFAULT 'Tier3',
  `tier_override` BOOLEAN NOT NULL DEFAULT false,
  `status` VARCHAR(191) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_by` INT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `speaker_profiles_speaker_id_key` (`speaker_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `speaker_contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speaker_profile_id` INT NOT NULL,
  `event_label` VARCHAR(191) NOT NULL DEFAULT 'EOCON 2026',
  `contact_status` VARCHAR(191) NOT NULL DEFAULT 'to_research',
  `format_proposed` VARCHAR(191) NULL,
  `topic_proposed` TEXT NULL,
  `assignee_id` INT NULL,
  `contacted_at` DATETIME(3) NULL,
  `response_at` DATETIME(3) NULL,
  `next_followup_at` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `speaker_contacts_speaker_profile_id_fkey` FOREIGN KEY (`speaker_profile_id`) REFERENCES `speaker_profiles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `speaker_sources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speaker_profile_id` INT NOT NULL,
  `type` VARCHAR(191) NOT NULL DEFAULT 'other',
  `title` VARCHAR(191) NULL,
  `url` TEXT NULL,
  `reliability` VARCHAR(191) NOT NULL DEFAULT 'secondary',
  `consulted_at` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `speaker_sources_speaker_profile_id_fkey` FOREIGN KEY (`speaker_profile_id`) REFERENCES `speaker_profiles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
