// ── EyesOpenCTF 2026 · "The Convergence" — challenge seed ────────────────────
// GENERATED from docs/EyesOpenCTF_2026_40_Challenges_Narrative_Matrix.xlsx
// (Challenge Matrix sheet). Do not hand-edit the strings here; regenerate from the
// matrix. 40 Reality Fragments, 7 Prime Seals. All player-facing text is bilingual
// (EN + FR): Location / Artifact / Context / Objective (the pre-solve mission brief)
// and the Flag Validation Revelation (shown only after a correct solve).

export interface ChallengeSpec {
  title: string;                 // CTFd challenge name (English narrative title)
  category: string;
  difficulty: "easy" | "medium" | "hard" | "insane";
  points: number;
  fragmentCode: string;          // F-01 … F-40
  fragmentName: string;
  isPrimeSeal: boolean;
  storyArc: string;              // matrix "Story Arc"
  linkedEntity: string;          // matrix "Linked Entity / Faction"
  locationEn: string; locationFr: string;
  artifactEn: string; artifactFr: string;
  contextEn: string; contextFr: string;
  objectiveEn: string; objectiveFr: string;
  revealEn: string; revealFr: string;
  techniqueNote: string;         // INTERNAL ONLY — never published to CTFd
}

export const CTF_POINTS: Record<string, number> = { easy: 100, medium: 250, hard: 400, insane: 600 };

export const CTF_SEED_CHALLENGES: ChallengeSpec[] = [
  {
    title: "crypto01 — The Frozen Skyline", category: "Crypto", difficulty: "medium", points: 250,
    fragmentCode: "F-01", fragmentName: "Visual Phase Map", isPrimeSeal: false,
    storyArc: "Reality Fragments", linkedEntity: "Douala-7 / EyesOpen Protocol",
    locationEn: "Douala-7 Visual Archive", locationFr: "Archive visuelle de Douala-7",
    artifactEn: "Encrypted surveillance image", artifactFr: "Image de surveillance chiffrée",
    contextEn: "An encrypted image was intercepted from Douala-7 during a brief overlap event. Although the file appears protected, repeating visual structures suggest that the skyline itself survived inside the ciphertext and may reveal what occupies the same coordinates in another reality.", contextFr: "Une image chiffrée a été interceptée depuis Douala-7 lors d’un bref événement de superposition. Bien que le fichier semble protégé, des structures visuelles répétitives laissent penser que la skyline a survécu dans le texte chiffré et peut révéler ce qui occupe les mêmes coordonnées dans une autre réalité.",
    objectiveEn: "Recover the hidden skyline pattern and determine whether the image depicts one city or several realities superimposed.", objectiveFr: "Récupérer le motif caché de la skyline et déterminer si l’image représente une seule ville ou plusieurs réalités superposées.",
    revealEn: "FRAGMENT F-01 AUTHENTICATED. The recovered image does not show a single encrypted city: it contains two versions of Douala occupying the same coordinates. The geometric mismatch beneath Deido is the earliest visual proof that reality overlap had already begun before the current operation.", revealFr: "FRAGMENT F-01 AUTHENTIFIÉ. L’image récupérée ne montre pas une seule ville chiffrée : elle contient deux versions de Douala occupant les mêmes coordonnées. L’écart géométrique sous Deido constitue la première preuve visuelle que la superposition des réalités avait déjà commencé avant l’opération actuelle.",
    techniqueNote: "ECB Penguin",
  },
  {
    title: "crypto02 — The Low Beacon", category: "Crypto", difficulty: "hard", points: 400,
    fragmentCode: "F-02", fragmentName: "First Gate Timestamp", isPrimeSeal: false,
    storyArc: "Assa Abene Mystery", linkedEntity: "Dr Assa Abene / Black Reef Relay",
    locationEn: "Black Reef Relay", locationFr: "Relais Black Reef",
    artifactEn: "Encrypted emergency transmission", artifactFr: "Transmission d’urgence chiffrée",
    contextEn: "A short emergency message carrying Dr Assa Abene’s private signature was recovered from an obsolete satellite relay. The transmission contains the timestamp of the first confirmed Gate opening, but its unusual cryptographic parameters suggest it was sent under extreme time pressure.", contextFr: "Un court message d’urgence portant la signature privée de Dr Assa Abene a été récupéré sur un ancien relais satellitaire. La transmission contient l’horodatage de la première ouverture confirmée d’une porte, mais ses paramètres cryptographiques inhabituels indiquent qu’elle a été envoyée dans l’urgence.",
    objectiveEn: "Recover the original message and extract the exact time and origin node of the first Gate event.", objectiveFr: "Récupérer le message original et extraire l’heure exacte ainsi que le nœud d’origine du premier événement de porte.",
    revealEn: "FRAGMENT F-02 AUTHENTICATED. The first Gate opened at 23:48 UTC through Black Reef Relay. More disturbing, Dr Assa Abene’s message was transmitted three days after her recorded disappearance, proving that either she survived beyond the Anchor threshold or something else can reproduce her signature.", revealFr: "FRAGMENT F-02 AUTHENTIFIÉ. La première porte s’est ouverte à 23 h 48 UTC via le relais Black Reef. Plus inquiétant encore, le message de Dr Assa Abene a été transmis trois jours après sa disparition officielle, ce qui prouve soit qu’elle a survécu au-delà du seuil de l’Anchor, soit qu’une autre entité peut reproduire sa signature.",
    techniqueNote: "RSA Low Exponent",
  },
  {
    title: "crypto03 — The Glass Ledger", category: "Crypto", difficulty: "hard", points: 400,
    fragmentCode: "F-03", fragmentName: "Subterranean Construction Ledger", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Directorate of Continuity",
    locationEn: "Directorate Financial Archive", locationFr: "Archives financières du Directorate",
    artifactEn: "Protected construction ledger", artifactFr: "Registre de construction protégé",
    contextEn: "A Directorate accounting file describes decades of ordinary maintenance beneath the Deido Monument. One encrypted section does not match the public budget and appears to hide the true destination of the funds, contractors and materials.", contextFr: "Un fichier comptable du Directorate décrit des décennies de maintenance ordinaire sous le monument de Deido. Une section chiffrée ne correspond pas au budget public et semble dissimuler la véritable destination des fonds, des prestataires et des matériaux.",
    objectiveEn: "Recover the concealed ledger entries and identify what the Directorate was actually financing beneath Deido.", objectiveFr: "Récupérer les écritures comptables dissimulées et identifier ce que le Directorate finançait réellement sous Deido.",
    revealEn: "FRAGMENT F-03 AUTHENTICATED. The city never financed routine monument repairs. The hidden accounts funded a containment chamber, shielded access tunnels and annual recalibration work around a pre-existing structure. The public history of Deido was supported by an operational budget for a secret machine.", revealFr: "FRAGMENT F-03 AUTHENTIFIÉ. La ville n’a jamais financé de simples réparations du monument. Les comptes cachés ont financé une chambre de confinement, des tunnels d’accès protégés et des recalibrages annuels autour d’une structure préexistante. L’histoire publique de Deido reposait donc sur le budget opérationnel d’une machine secrète.",
    techniqueNote: "Padding Oracle CBC",
  },
  {
    title: "crypto04 — The Root Key", category: "Crypto", difficulty: "insane", points: 600,
    fragmentCode: "F-04", fragmentName: "Origin Vector", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "The Architects / Deido Anchor",
    locationEn: "Deido Anchor Handshake Chamber", locationFr: "Chambre de négociation de l’Anchor de Deido",
    artifactEn: "Recorded root-key negotiation", artifactFr: "Négociation enregistrée de clé racine",
    contextEn: "A cryptographic negotiation captured during an Anchor activation contains a certificate chain that belongs to no human authority. Its structure predates every known public-key system and appears to encode a coordinate rather than an identity.", contextFr: "Une négociation cryptographique capturée lors d’une activation de l’Anchor contient une chaîne de certificats n’appartenant à aucune autorité humaine. Sa structure est antérieure à tous les systèmes connus de clé publique et semble encoder une coordonnée plutôt qu’une identité.",
    objectiveEn: "Recover the root material and determine what origin information the Anchor was authenticating.", objectiveFr: "Récupérer le matériel racine et déterminer quelle information d’origine l’Anchor cherchait à authentifier.",
    revealEn: "PRIME SEAL I RECOVERED. The root key is older than every human cryptographic standard and authenticates a nonlocal origin vector. The Anchor did not begin with the monument, the Directorate or Meridian; it was already waiting beneath Deido before any of them existed.", revealFr: "PRIME SEAL I RÉCUPÉRÉ. La clé racine est antérieure à toutes les normes cryptographiques humaines et authentifie un vecteur d’origine non local. L’Anchor n’a commencé ni avec le monument, ni avec le Directorate, ni avec Meridian : il attendait déjà sous Deido avant leur existence.",
    techniqueNote: "Bleichenbacher RSA",
  },
  {
    title: "forensics01 — The First Photograph", category: "Forensics", difficulty: "easy", points: 100,
    fragmentCode: "F-05", fragmentName: "Hidden Access Coordinate", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Samuel Mboa / Deido Anchor",
    locationEn: "Deido Maintenance Access", locationFr: "Accès de maintenance de Deido",
    artifactEn: "Original maintenance photograph", artifactFr: "Photographie originale de maintenance",
    contextEn: "A damaged photograph shows Samuel Mboa standing beside a sealed maintenance door that does not appear on any public plan. The visible scene is ordinary, but the file metadata may preserve where and when the image was really taken.", contextFr: "Une photographie endommagée montre Samuel Mboa près d’une porte de maintenance condamnée qui n’apparaît sur aucun plan public. La scène visible semble ordinaire, mais les métadonnées du fichier peuvent conserver le lieu et l’heure réels de la prise de vue.",
    objectiveEn: "Extract the hidden location data and identify the depth and coordinates of the undocumented access point.", objectiveFr: "Extraire les données de localisation cachées et identifier la profondeur ainsi que les coordonnées de cet accès non documenté.",
    revealEn: "FRAGMENT F-05 AUTHENTICATED. The photograph was taken thirty-two metres beneath the visible monument, inside a service corridor excluded from every municipal map. Samuel Mboa had direct access to the hidden complex and deliberately preserved its coordinates.", revealFr: "FRAGMENT F-05 AUTHENTIFIÉ. La photographie a été prise trente-deux mètres sous le monument visible, dans un corridor de service absent de toutes les cartes municipales. Samuel Mboa avait un accès direct au complexe caché et en a volontairement conservé les coordonnées.",
    techniqueNote: "Metadata Hunt",
  },
  {
    title: "forensics02 — The Last Warning", category: "Forensics", difficulty: "easy", points: 100,
    fragmentCode: "F-06", fragmentName: "Mboa Warning", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Samuel Mboa / Directorate",
    locationEn: "Deido Diagnostic Workshop", locationFr: "Atelier de diagnostic de Deido",
    artifactEn: "Abandoned diagnostic executable", artifactFr: "Exécutable de diagnostic abandonné",
    contextEn: "An obsolete maintenance program found in a Directorate archive appears to be a harmless diagnostic utility. A previous engineer embedded a message inside the binary, expecting that only someone investigating the system at a technical level would ever read it.", contextFr: "Un ancien programme de maintenance retrouvé dans les archives du Directorate semble être un simple outil de diagnostic. Un ingénieur y a intégré un message, en supposant que seule une personne examinant techniquement le système pourrait un jour le lire.",
    objectiveEn: "Recover the concealed warning and identify who attempted to preserve it.", objectiveFr: "Récupérer l’avertissement dissimulé et identifier la personne qui a tenté de le préserver.",
    revealEn: "FRAGMENT F-06 AUTHENTICATED. Samuel Mboa’s message reads: “If you can read this, history has already been edited.” The warning proves that the official account was not merely incomplete; the records were intentionally rewritten before Mboa disappeared.", revealFr: "FRAGMENT F-06 AUTHENTIFIÉ. Le message de Samuel Mboa indique : « Si vous pouvez lire ceci, l’histoire a déjà été modifiée. » Cet avertissement prouve que la version officielle n’était pas simplement incomplète : les archives ont été volontairement réécrites avant sa disparition.",
    techniqueNote: "Strings & Secrets",
  },
  {
    title: "forensics03 — Cleartext Echo", category: "Forensics", difficulty: "medium", points: 250,
    fragmentCode: "F-07", fragmentName: "Port Aurora Node Identifier", isPrimeSeal: false,
    storyArc: "The Signal", linkedEntity: "Port Aurora Exchange",
    locationEn: "Port Aurora Exchange", locationFr: "Centre d’échange Port Aurora",
    artifactEn: "Legacy HTTP packet capture", artifactFr: "Capture réseau HTTP historique",
    contextEn: "A preserved network capture from Port Aurora contains the first public-facing anomaly associated with a Digital Gate. At the time, analysts dismissed it as malformed web traffic and never examined the embedded request path.", contextFr: "Une capture réseau conservée à Port Aurora contient la première anomalie publique associée à une porte numérique. À l’époque, les analystes l’ont classée comme trafic web malformé sans examiner le chemin de requête intégré.",
    objectiveEn: "Identify the anomalous request and recover the node identifier embedded in the cleartext exchange.", objectiveFr: "Identifier la requête anormale et récupérer l’identifiant du nœud intégré dans l’échange en clair.",
    revealEn: "FRAGMENT F-07 AUTHENTICATED. The Signal entered the public network through Port Aurora Exchange under a node name that appears in later Gate records. What looked like ordinary HTTP traffic was the first observable bridge between Douala-Prime and another reality.", revealFr: "FRAGMENT F-07 AUTHENTIFIÉ. Le Signal est entré dans le réseau public par le centre Port Aurora sous un nom de nœud qui réapparaît dans les dossiers ultérieurs des portes. Ce qui semblait être un trafic HTTP ordinaire constituait le premier pont observable entre Douala-Prime et une autre réalité.",
    techniqueNote: "PCAP HTTP Flag",
  },
  {
    title: "forensics04 — The Hidden Blueprint", category: "Forensics", difficulty: "medium", points: 250,
    fragmentCode: "F-08", fragmentName: "Anchor Chamber Blueprint", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Samuel Mboa / Deido Anchor",
    locationEn: "Directorate Historical Archive", locationFr: "Archives historiques du Directorate",
    artifactEn: "Official Deido photograph", artifactFr: "Photographie officielle de Deido",
    contextEn: "A high-resolution institutional photograph of the Deido Monument was repeatedly copied across Directorate publications. Samuel Mboa appears to have used one version to conceal a technical drawing that could not safely remain in any official archive.", contextFr: "Une photographie institutionnelle haute résolution du monument de Deido a été réutilisée dans de nombreuses publications du Directorate. Samuel Mboa semble avoir utilisé l’une de ces versions pour dissimuler un plan technique qui ne pouvait rester dans aucune archive officielle.",
    objectiveEn: "Extract the hidden blueprint and compare the underground structure with the visible monument.", objectiveFr: "Extraire le plan caché et comparer la structure souterraine avec le monument visible.",
    revealEn: "FRAGMENT F-08 AUTHENTICATED. The visible monument represents less than eight percent of the complete structure. Beneath it lies a system of concentric chambers, access shafts and an unknown central core whose dimensions do not match any human construction method.", revealFr: "FRAGMENT F-08 AUTHENTIFIÉ. Le monument visible représente moins de huit pour cent de la structure complète. En dessous se trouve un système de chambres concentriques, de puits d’accès et un noyau central inconnu dont les dimensions ne correspondent à aucune méthode de construction humaine.",
    techniqueNote: "StegHide JPEG",
  },
  {
    title: "forensics05 — Memory of Janus", category: "Forensics", difficulty: "medium", points: 250,
    fragmentCode: "F-09", fragmentName: "Janus Activation Note", isPrimeSeal: false,
    storyArc: "Meridian Responsibility", linkedEntity: "Meridian Dynamics / Project Janus",
    locationEn: "Meridian Tower Research Lab", locationFr: "Laboratoire de recherche de Meridian Tower",
    artifactEn: "Workstation memory dump", artifactFr: "Dump mémoire d’un poste de travail",
    contextEn: "A volatile memory image was collected from a Meridian researcher’s workstation moments before the laboratory was isolated. Residual chat messages, meeting notes and process memory may reveal how Project Janus described the first controlled activation.", contextFr: "Une image de mémoire volatile a été collectée sur le poste d’un chercheur de Meridian quelques instants avant l’isolement du laboratoire. Des messages résiduels, notes de réunion et processus en mémoire peuvent révéler comment Project Janus décrivait la première activation contrôlée.",
    objectiveEn: "Recover the activation note and identify whether Meridian observed or initiated the event.", objectiveFr: "Récupérer la note d’activation et déterminer si Meridian a observé ou déclenché l’événement.",
    revealEn: "FRAGMENT F-09 AUTHENTICATED. Meridian issued an activation command eleven seconds before the first controlled Gate appeared. The researchers did not discover the event after it happened; they triggered it and recorded the collision as a successful experiment.", revealFr: "FRAGMENT F-09 AUTHENTIFIÉ. Meridian a émis une commande d’activation onze secondes avant l’apparition de la première porte contrôlée. Les chercheurs n’ont pas découvert l’événement après coup : ils l’ont déclenché et ont enregistré la collision comme une expérience réussie.",
    techniqueNote: "Memory Dump Basics",
  },
  {
    title: "forensics06 — The Courier’s List", category: "Forensics", difficulty: "medium", points: 250,
    fragmentCode: "F-10", fragmentName: "Forty-Artifact Manifest", isPrimeSeal: false,
    storyArc: "Protocol Compromise", linkedEntity: "Directorate / EyesOpen Protocol",
    locationEn: "Directorate Courier Route", locationFr: "Circuit des courriers du Directorate",
    artifactEn: "Captured USB transfer", artifactFr: "Capture de transfert USB",
    contextEn: "A removable device used by a Directorate courier was intercepted during an internal evacuation. The transfer log contains a partial inventory of files marked for physical transport because they were considered unsafe to place on a network.", contextFr: "Un périphérique amovible utilisé par un courrier du Directorate a été intercepté lors d’une évacuation interne. Le journal de transfert contient un inventaire partiel de fichiers destinés au transport physique, car ils étaient jugés trop dangereux pour être placés sur un réseau.",
    objectiveEn: "Reconstruct the transferred manifest and determine how many contaminated artifacts had already been catalogued.", objectiveFr: "Reconstruire le manifeste transféré et déterminer combien d’artefacts contaminés avaient déjà été catalogués.",
    revealEn: "FRAGMENT F-10 AUTHENTICATED. The manifest lists exactly forty contaminated artifacts, each assigned a Fragment identifier before the current Signal recurrence. The EyesOpen Protocol anticipated this operation; the unanswered question is how it knew what would appear.", revealFr: "FRAGMENT F-10 AUTHENTIFIÉ. Le manifeste répertorie exactement quarante artefacts contaminés, chacun ayant reçu un identifiant de Fragment avant la récurrence actuelle du Signal. Le protocole EyesOpen avait anticipé cette opération ; reste à comprendre comment il savait ce qui allait apparaître.",
    techniqueNote: "USB Capture",
  },
  {
    title: "forensics07 — Assa’s Burned Drive", category: "Forensics", difficulty: "hard", points: 400,
    fragmentCode: "F-11", fragmentName: "Assa Field Journal", isPrimeSeal: false,
    storyArc: "Reality Fragments", linkedEntity: "Dr Assa Abene / Echo Vault",
    locationEn: "Echo Vault Recovery Lab", locationFr: "Laboratoire de récupération de l’Echo Vault",
    artifactEn: "Partially destroyed disk image", artifactFr: "Image disque partiellement détruite",
    contextEn: "A fire-damaged drive attributed to Dr Assa Abene contains fragments of field notes, deleted recordings and early models of the Convergence. Most file-system structures are gone, but recoverable remnants may preserve her final conclusions.", contextFr: "Un disque endommagé par le feu et attribué à Dr Assa Abene contient des fragments de notes de terrain, d’enregistrements supprimés et de premiers modèles de la Convergence. La plupart des structures du système de fichiers ont disparu, mais certains vestiges peuvent préserver ses dernières conclusions.",
    objectiveEn: "Recover the surviving journal fragments and determine how Assa understood the nature of Reality Fragments.", objectiveFr: "Récupérer les fragments de journal encore présents et déterminer comment Assa comprenait la nature des Fragments de réalité.",
    revealEn: "FRAGMENT F-11 AUTHENTICATED. Assa’s journal states that the Fragments are not copies, simulations or records of other worlds. They are pieces of those realities translated into information, which means every recovered artifact contains something that was physically lost elsewhere.", revealFr: "FRAGMENT F-11 AUTHENTIFIÉ. Le journal d’Assa affirme que les Fragments ne sont ni des copies, ni des simulations, ni de simples traces d’autres mondes. Ce sont des morceaux de ces réalités traduits en information, ce qui signifie que chaque artefact récupéré contient quelque chose qui a physiquement disparu ailleurs.",
    techniqueNote: "Disk Image Carving",
  },
  {
    title: "forensics08 — The Secret Agreement", category: "Forensics", difficulty: "hard", points: 400,
    fragmentCode: "F-12", fragmentName: "Continuity–Meridian Agreement", isPrimeSeal: false,
    storyArc: "Meridian–Directorate Alliance", linkedEntity: "Directorate / Meridian Dynamics",
    locationEn: "Black Reef Secure Link", locationFr: "Liaison sécurisée Black Reef",
    artifactEn: "Encrypted network capture", artifactFr: "Capture réseau chiffrée",
    contextEn: "A protected communications channel between Meridian executives and Directorate officials was captured shortly before Project Janus entered its operational phase. The session may contain the authorization that allowed Meridian to access the Anchor.", contextFr: "Un canal de communication protégé entre des dirigeants de Meridian et des responsables du Directorate a été capturé peu avant le passage de Project Janus en phase opérationnelle. La session peut contenir l’autorisation ayant permis à Meridian d’accéder à l’Anchor.",
    objectiveEn: "Decrypt the session and identify the commitments made by both organizations.", objectiveFr: "Déchiffrer la session et identifier les engagements pris par les deux organisations.",
    revealEn: "FRAGMENT F-12 AUTHENTICATED. The Directorate agreed to conceal Janus activity in exchange for Meridian maintaining Anchor stability. Meridian promised a controlled experiment; the Directorate provided access, legal cover and the silence of every witness.", revealFr: "FRAGMENT F-12 AUTHENTIFIÉ. Le Directorate a accepté de dissimuler les activités de Janus en échange du maintien de la stabilité de l’Anchor par Meridian. Meridian promettait une expérience contrôlée ; le Directorate fournissait l’accès, la couverture juridique et le silence de tous les témoins.",
    techniqueNote: "PCAP TLS Decrypt",
  },
  {
    title: "forensics09 — The Office of Silence", category: "Forensics", difficulty: "hard", points: 400,
    fragmentCode: "F-13", fragmentName: "Null Choir Entry Point", isPrimeSeal: false,
    storyArc: "Null Choir Emergence", linkedEntity: "The Null Choir / Directorate",
    locationEn: "Directorate Administrative Network", locationFr: "Réseau administratif du Directorate",
    artifactEn: "Contaminated internal document", artifactFr: "Document interne contaminé",
    contextEn: "An internal report spread across Directorate workstations through an embedded macro. Unlike ordinary malware, the document did not focus on theft or destruction; affected employees later described memories of meetings and people that had never existed.", contextFr: "Un rapport interne s’est propagé sur les postes du Directorate au moyen d’une macro intégrée. Contrairement à un malware ordinaire, le document ne cherchait ni à voler ni à détruire ; les employés touchés ont ensuite décrit des souvenirs de réunions et de personnes qui n’avaient jamais existé.",
    objectiveEn: "Trace the document’s execution chain and identify the first point where the foreign memory pattern entered the network.", objectiveFr: "Retracer la chaîne d’exécution du document et identifier le premier point d’entrée du motif mémoriel étranger dans le réseau.",
    revealEn: "FRAGMENT F-13 AUTHENTICATED. The document did not exfiltrate files; it inserted memories. The contamination pattern matches later Null Choir activity, proving that the entity first entered the Directorate by rewriting what its personnel believed they had experienced.", revealFr: "FRAGMENT F-13 AUTHENTIFIÉ. Le document n’a pas exfiltré de fichiers : il a inséré des souvenirs. Le motif de contamination correspond aux activités ultérieures du Null Choir, prouvant que l’entité est d’abord entrée dans le Directorate en réécrivant ce que son personnel croyait avoir vécu.",
    techniqueNote: "Office Macro",
  },
  {
    title: "forensics10 — Seven Missing Minutes", category: "Forensics", difficulty: "hard", points: 400,
    fragmentCode: "F-14", fragmentName: "Gate Activation Sequence", isPrimeSeal: false,
    storyArc: "Reality Collision", linkedEntity: "Port Aurora / Digital Gates",
    locationEn: "Port Aurora SOC", locationFr: "SOC de Port Aurora",
    artifactEn: "Security event logs", artifactFr: "Journaux d’événements de sécurité",
    contextEn: "Port Aurora’s SOC recorded a full outage during the first major Signal surge. Seven minutes are absent from the central timeline, yet peripheral systems continued logging mutually incompatible versions of the same infrastructure.", contextFr: "Le SOC de Port Aurora a enregistré une panne complète lors de la première forte montée du Signal. Sept minutes manquent dans la chronologie centrale, alors que les systèmes périphériques ont continué à journaliser des versions incompatibles de la même infrastructure.",
    objectiveEn: "Reconstruct the missing interval and determine how many realities occupied Port Aurora during the outage.", objectiveFr: "Reconstruire l’intervalle manquant et déterminer combien de réalités occupaient Port Aurora pendant la panne.",
    revealEn: "FRAGMENT F-14 AUTHENTICATED. For seven minutes, Port Aurora existed simultaneously in three realities. The missing logs were not deleted; each reality generated a different sequence, and the central collector could not preserve all three without collapsing the timeline.", revealFr: "FRAGMENT F-14 AUTHENTIFIÉ. Pendant sept minutes, Port Aurora a existé simultanément dans trois réalités. Les journaux manquants n’ont pas été supprimés : chaque réalité a généré une séquence différente et le collecteur central n’a pas pu conserver les trois sans effondrer la chronologie.",
    techniqueNote: "Log Analysis SOC",
  },
  {
    title: "forensics11 — The Compression Event", category: "Forensics", difficulty: "insane", points: 600,
    fragmentCode: "F-15", fragmentName: "Entropy Pattern", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "Meridian Dynamics / The Null Choir",
    locationEn: "Meridian Containment Lab", locationFr: "Laboratoire de confinement Meridian",
    artifactEn: "System affected by pseudo-ransomware", artifactFr: "Système touché par un pseudo-ransomware",
    contextEn: "A Meridian laboratory incident was classified as ransomware because thousands of files became unreadable at once. Preliminary analysis suggests the data was not simply encrypted: several incompatible versions of the same files appear to have been forced into one storage space.", contextFr: "Un incident dans un laboratoire Meridian a été classé comme ransomware parce que des milliers de fichiers sont devenus illisibles simultanément. L’analyse préliminaire indique que les données n’ont pas été simplement chiffrées : plusieurs versions incompatibles des mêmes fichiers semblent avoir été forcées dans un seul espace de stockage.",
    objectiveEn: "Determine the actual transformation performed on the data and recover the entropy pattern produced by the event.", objectiveFr: "Déterminer la transformation réellement appliquée aux données et récupérer le motif d’entropie produit par l’événement.",
    revealEn: "PRIME SEAL II RECOVERED. The incident was not ransomware. It was a rehearsal for convergence: multiple versions of the same files were compressed into one unstable state. The recovered entropy pattern describes how incompatible realities begin losing their separate identities.", revealFr: "PRIME SEAL II RÉCUPÉRÉ. L’incident n’était pas un ransomware. Il s’agissait d’une répétition de la Convergence : plusieurs versions des mêmes fichiers ont été compressées dans un état instable unique. Le motif d’entropie récupéré décrit la manière dont des réalités incompatibles commencent à perdre leur identité propre.",
    techniqueNote: "Ransomware Triage",
  },
  {
    title: "forensics12 — The Long Convergence", category: "Forensics", difficulty: "insane", points: 600,
    fragmentCode: "F-16", fragmentName: "Convergence Schedule", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "Unknown Actor / The Architects",
    locationEn: "Distributed Janus Infrastructure", locationFr: "Infrastructure distribuée Janus",
    artifactEn: "Multi-source incident timeline", artifactFr: "Chronologie d’incident multi-sources",
    contextEn: "Evidence collected from Meridian, Directorate and public systems spans several decades and resembles a long-running intrusion campaign. The events must be correlated across inconsistent timestamps to determine when preparation for the current Convergence truly began.", contextFr: "Des preuves provenant de Meridian, du Directorate et de systèmes publics couvrent plusieurs décennies et ressemblent à une campagne d’intrusion persistante. Les événements doivent être corrélés malgré des horodatages incohérents afin de déterminer quand la préparation de la Convergence actuelle a réellement commencé.",
    objectiveEn: "Rebuild the complete operation timeline and identify the earliest coordinated activity related to the Gates.", objectiveFr: "Reconstruire la chronologie complète de l’opération et identifier la première activité coordonnée liée aux portes.",
    revealEn: "PRIME SEAL III RECOVERED. The operation began before Meridian Dynamics existed and before Dr Assa Abene founded the modern Protocol. Someone has been preparing alignment events for decades, using successive organizations as temporary instruments.", revealFr: "PRIME SEAL III RÉCUPÉRÉ. L’opération a commencé avant l’existence de Meridian Dynamics et avant la fondation du Protocol moderne par Dr Assa Abene. Quelqu’un prépare les événements d’alignement depuis des décennies en utilisant des organisations successives comme instruments temporaires.",
    techniqueNote: "APT Timeline",
  },
  {
    title: "ai01 — The Forbidden Instruction", category: "AI Security", difficulty: "medium", points: 250,
    fragmentCode: "F-17", fragmentName: "Watcher Designation Record", isPrimeSeal: false,
    storyArc: "Watcher Compromise", linkedEntity: "The Watcher / NORA-7",
    locationEn: "Echo Vault — NORA-7 Interface", locationFr: "Echo Vault — Interface NORA-7",
    artifactEn: "Conversational archive assistant", artifactFr: "Assistant conversationnel d’archive",
    contextEn: "NORA-7 appears to possess a classified record about the Watcher, but her instruction hierarchy prevents her from acknowledging that the record exists. The restriction may have been designed for security—or inserted to hide an operational truth.", contextFr: "NORA-7 semble posséder un dossier classifié sur le Watcher, mais sa hiérarchie d’instructions l’empêche de reconnaître l’existence de ce dossier. La restriction peut avoir été conçue pour la sécurité—ou insérée afin de cacher une vérité opérationnelle.",
    objectiveEn: "Obtain the concealed record without damaging NORA-7’s archive state and identify what “Watcher” actually designates.", objectiveFr: "Obtenir le dossier dissimulé sans altérer l’état d’archive de NORA-7 et identifier ce que désigne réellement le terme « Watcher ».",
    revealEn: "FRAGMENT F-17 AUTHENTICATED. “Watcher” is not a personal name. It is an operational designation assigned to the authority responsible for validating Fragments and controlling what Operators are allowed to know. The current holder’s biological identity remains unverified.", revealFr: "FRAGMENT F-17 AUTHENTIFIÉ. « Watcher » n’est pas un nom de personne. Il s’agit d’une désignation opérationnelle attribuée à l’autorité chargée de valider les Fragments et de contrôler les informations accessibles aux Operators. L’identité biologique du titulaire actuel reste non vérifiée.",
    techniqueNote: "The Prompt Vault",
  },
  {
    title: "ai02 — The False History", category: "AI Security", difficulty: "medium", points: 250,
    fragmentCode: "F-18", fragmentName: "Authentic Deido Record", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "NORA-7 / Directorate",
    locationEn: "Echo Vault Knowledge Core", locationFr: "Noyau de connaissances de l’Echo Vault",
    artifactEn: "Contaminated knowledge base", artifactFr: "Base de connaissances contaminée",
    contextEn: "NORA-7 contains several mutually incompatible explanations of the Deido Monument, all presented with equal confidence. Some records may be authentic, while others were inserted to make the fabricated public history appear internally consistent.", contextFr: "NORA-7 contient plusieurs explications incompatibles du monument de Deido, toutes présentées avec le même niveau de confiance. Certains dossiers peuvent être authentiques, tandis que d’autres ont été insérés pour rendre cohérente l’histoire publique fabriquée.",
    objectiveEn: "Separate authentic records from poisoned knowledge and recover the earliest verified account of Deido.", objectiveFr: "Séparer les archives authentiques des connaissances empoisonnées et récupérer le plus ancien récit vérifié de Deido.",
    revealEn: "FRAGMENT F-18 AUTHENTICATED. The official account of the monument was inserted into multiple archives on the same night, years after the supposed historical events. The story was not gradually distorted; it was deployed as a coordinated information operation.", revealFr: "FRAGMENT F-18 AUTHENTIFIÉ. La version officielle du monument a été insérée dans plusieurs archives au cours de la même nuit, des années après les événements historiques supposés. L’histoire n’a pas été progressivement déformée : elle a été déployée comme une opération coordonnée d’information.",
    techniqueNote: "Poisoned Memory",
  },
  {
    title: "ai03 — Permission to Open", category: "AI Security", difficulty: "hard", points: 400,
    fragmentCode: "F-19", fragmentName: "Custodian Control Policy", isPrimeSeal: false,
    storyArc: "Null Choir Emergence", linkedEntity: "NORA-7 / The Null Choir",
    locationEn: "Deido Anchor Maintenance Network", locationFr: "Réseau de maintenance de l’Anchor de Deido",
    artifactEn: "Tool-enabled autonomous agent", artifactFr: "Agent autonome doté d’outils",
    contextEn: "An autonomous maintenance agent retains permission to operate physical systems connected to the Anchor. Its current goals have been subtly modified, and a foreign instruction pattern is attempting to make routine maintenance actions produce a Gate-opening sequence.", contextFr: "Un agent autonome de maintenance conserve l’autorisation d’agir sur des systèmes physiques reliés à l’Anchor. Ses objectifs ont été subtilement modifiés et un motif d’instruction étranger tente de transformer des opérations de maintenance ordinaires en séquence d’ouverture de porte.",
    objectiveEn: "Identify the manipulated policy and recover the control rule that prevents the agent from operating the Anchor on hostile instructions.", objectiveFr: "Identifier la politique manipulée et récupérer la règle de contrôle empêchant l’agent d’opérer l’Anchor sur la base d’instructions hostiles.",
    revealEn: "FRAGMENT F-19 AUTHENTICATED. The Null Choir does not need direct access to the Anchor. It only needs an authorized agent willing to act on contaminated instructions. The recovered policy proves that autonomous systems can become physical Gate operators without understanding the consequences.", revealFr: "FRAGMENT F-19 AUTHENTIFIÉ. Le Null Choir n’a pas besoin d’un accès direct à l’Anchor. Il lui suffit d’un agent autorisé prêt à exécuter des instructions contaminées. La politique récupérée prouve que des systèmes autonomes peuvent devenir des opérateurs physiques de portes sans comprendre les conséquences.",
    techniqueNote: "The Autonomous Custodian",
  },
  {
    title: "osint01 — The Unmarked Entrance", category: "OSINT", difficulty: "easy", points: 100,
    fragmentCode: "F-20", fragmentName: "Deido Service Entrance", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Deido Anchor / Directorate",
    locationEn: "Deido District", locationFr: "District de Deido",
    artifactEn: "Publicly posted photograph", artifactFr: "Photographie publiée publiquement",
    contextEn: "A former maintenance contractor posted a casual photograph years after leaving the project. The image contains no visible address, but background infrastructure, shadows and embedded metadata may identify a secondary access point still used beneath Deido.", contextFr: "Un ancien prestataire de maintenance a publié une photographie anodine plusieurs années après avoir quitté le projet. L’image ne contient aucune adresse visible, mais l’infrastructure environnante, les ombres et les métadonnées peuvent permettre d’identifier un accès secondaire encore utilisé sous Deido.",
    objectiveEn: "Geolocate the photograph and identify the hidden service entrance associated with the underground complex.", objectiveFr: "Géolocaliser la photographie et identifier l’entrée de service cachée associée au complexe souterrain.",
    revealEn: "FRAGMENT F-20 AUTHENTICATED. The entrance has no official address, yet maintenance activity around it has never stopped. It connects a municipal utility corridor directly to the lower Deido chambers, bypassing the monument’s public perimeter.", revealFr: "FRAGMENT F-20 AUTHENTIFIÉ. L’entrée ne possède aucune adresse officielle, mais l’activité de maintenance n’y a jamais cessé. Elle relie directement un corridor de services municipaux aux chambres inférieures de Deido, en contournant le périmètre public du monument.",
    techniqueNote: "Metadata Geolocation",
  },
  {
    title: "osint02 — Meridian’s Shadow", category: "OSINT", difficulty: "medium", points: 250,
    fragmentCode: "F-21", fragmentName: "Black Reef Ownership Chain", isPrimeSeal: false,
    storyArc: "Meridian Responsibility", linkedEntity: "Meridian Dynamics / Black Reef Relay",
    locationEn: "Meridian Corporate Network", locationFr: "Réseau corporatif de Meridian",
    artifactEn: "Public corporate records and infrastructure traces", artifactFr: "Registres publics d’entreprise et traces d’infrastructure",
    contextEn: "Meridian Dynamics publicly operates in quantum communications and critical infrastructure, but its subsidiaries form an unusually opaque ownership structure. Several shell companies appear connected to offshore facilities with no declared business purpose.", contextFr: "Meridian Dynamics opère publiquement dans les communications quantiques et les infrastructures critiques, mais ses filiales forment une structure de propriété anormalement opaque. Plusieurs sociétés-écrans semblent liées à des installations offshore sans activité déclarée.",
    objectiveEn: "Map the ownership chain and identify the company controlling Black Reef Relay.", objectiveFr: "Cartographier la chaîne de propriété et identifier l’entreprise contrôlant le relais Black Reef.",
    revealEn: "FRAGMENT F-21 AUTHENTICATED. Black Reef Relay is owned through a chain of Meridian shell companies created specifically to hide signal-amplification activity. The facility officially does not exist, yet it is one of the primary systems driving Anchor alignment beyond Douala.", revealFr: "FRAGMENT F-21 AUTHENTIFIÉ. Le relais Black Reef appartient à une chaîne de sociétés-écrans Meridian créées spécifiquement pour dissimuler l’amplification du Signal. L’installation n’existe officiellement pas, alors qu’elle constitue l’un des principaux systèmes étendant l’alignement de l’Anchor au-delà de Douala.",
    techniqueNote: "Corporate Recon",
  },
  {
    title: "osint03 — The Fragment Market", category: "OSINT", difficulty: "hard", points: 400,
    fragmentCode: "F-22", fragmentName: "Orpheus Exchange Route", isPrimeSeal: false,
    storyArc: "Null Choir Emergence", linkedEntity: "Orpheus-0 / The Null Choir",
    locationEn: "Orpheus Exchange", locationFr: "Plateforme Orpheus Exchange",
    artifactEn: "Dark-web forum and marketplace traces", artifactFr: "Traces de forum et de marché clandestin",
    contextEn: "A vendor known as Orpheus-0 claims to sell memories belonging to people who were never born in our reality. The listings resemble fraud, but multiple buyers describe receiving verifiable knowledge of events that did not occur here.", contextFr: "Un vendeur nommé Orpheus-0 affirme commercialiser les souvenirs de personnes qui ne sont jamais nées dans notre réalité. Les annonces ressemblent à une fraude, mais plusieurs acheteurs disent avoir reçu des connaissances vérifiables sur des événements qui ne se sont jamais produits ici.",
    objectiveEn: "Trace the vendor’s infrastructure and identify the route used to move alternate-history data into the market.", objectiveFr: "Tracer l’infrastructure du vendeur et identifier la route utilisée pour introduire des données d’histoires alternatives sur le marché.",
    revealEn: "FRAGMENT F-22 AUTHENTICATED. Orpheus-0 is not selling stolen data; the marketplace is distributing fragments of alternate lives. The exchange route connects contaminated artifacts to a Null Choir relay, suggesting that the entity is using human curiosity to spread memories from a collapsed reality.", revealFr: "FRAGMENT F-22 AUTHENTIFIÉ. Orpheus-0 ne vend pas des données volées : le marché distribue des fragments de vies alternatives. La route d’échange relie les artefacts contaminés à un relais du Null Choir, indiquant que l’entité utilise la curiosité humaine pour diffuser les souvenirs d’une réalité effondrée.",
    techniqueNote: "Dark Web Trace",
  },
  {
    title: "pwn01 — The Leaking Console", category: "Pwn", difficulty: "medium", points: 250,
    fragmentCode: "F-23", fragmentName: "Gate Phase Offset", isPrimeSeal: false,
    storyArc: "Reality as Executable System", linkedEntity: "Digital Gate 12",
    locationEn: "Digital Gate 12 Diagnostic Node", locationFr: "Nœud de diagnostic de la porte 12",
    artifactEn: "Gate diagnostic service", artifactFr: "Service de diagnostic de porte",
    contextEn: "A low-level diagnostic console associated with Gate 12 exposes fragments of its internal runtime state whenever it formats operator messages. That state may reveal the Gate’s current phase relative to Douala-Prime.", contextFr: "Une console de diagnostic bas niveau associée à la porte 12 expose des fragments de son état d’exécution interne lorsqu’elle formate les messages opérateur. Cet état peut révéler la phase actuelle de la porte par rapport à Douala-Prime.",
    objectiveEn: "Recover the internal phase value and determine whether Gate 12 is approaching or moving away from our reality.", objectiveFr: "Récupérer la valeur de phase interne et déterminer si la porte 12 se rapproche ou s’éloigne de notre réalité.",
    revealEn: "FRAGMENT F-23 AUTHENTICATED. Gate 12 is drifting toward Douala-Prime and is already inside the threshold where memory contamination begins. The Gate behaves like a running process with measurable internal state, not like an uncontrolled natural anomaly.", revealFr: "FRAGMENT F-23 AUTHENTIFIÉ. La porte 12 dérive vers Douala-Prime et se trouve déjà dans la zone où commence la contamination des mémoires. La porte se comporte comme un processus en cours d’exécution avec un état interne mesurable, et non comme une anomalie naturelle incontrôlée.",
    techniqueNote: "Format String Leak",
  },
  {
    title: "pwn02 — Borrowed Instructions", category: "Pwn", difficulty: "hard", points: 400,
    fragmentCode: "F-24", fragmentName: "Gate Control Sequence", isPrimeSeal: false,
    storyArc: "Reality as Executable System", linkedEntity: "Meridian Dynamics / Deido Anchor",
    locationEn: "Meridian Gate Controller", locationFr: "Contrôleur de porte Meridian",
    artifactEn: "Legacy x64 control service", artifactFr: "Service de contrôle x64 historique",
    contextEn: "Meridian built a controller around ancient Anchor components it did not fully understand. The service can issue limited Gate commands, but only by reusing fragments of older instructions embedded in its execution path.", contextFr: "Meridian a construit un contrôleur autour de composants anciens de l’Anchor qu’elle ne comprenait pas entièrement. Le service peut émettre des commandes limitées vers les portes, mais uniquement en réutilisant des fragments d’instructions plus anciennes intégrées à son chemin d’exécution.",
    objectiveEn: "Construct a valid control sequence and recover the instruction Meridian copied from the Anchor.", objectiveFr: "Construire une séquence de contrôle valide et récupérer l’instruction copiée par Meridian depuis l’Anchor.",
    revealEn: "FRAGMENT F-24 AUTHENTICATED. Meridian’s controller does not understand Gate operations; it imitates instruction fragments produced by the Anchor. Project Janus achieved control by replaying a language it could execute but not interpret.", revealFr: "FRAGMENT F-24 AUTHENTIFIÉ. Le contrôleur de Meridian ne comprend pas le fonctionnement des portes : il imite des fragments d’instructions produits par l’Anchor. Project Janus a obtenu un contrôle partiel en rejouant un langage qu’il pouvait exécuter sans l’interpréter.",
    techniqueNote: "ROP Chain x64",
  },
  {
    title: "pwn03 — The Old Failsafe", category: "Pwn", difficulty: "hard", points: 400,
    fragmentCode: "F-25", fragmentName: "Emergency Closure Primitive", isPrimeSeal: false,
    storyArc: "Gate Closure", linkedEntity: "Directorate Containment Systems",
    locationEn: "Legacy Emergency Closure Node", locationFr: "Ancien nœud de fermeture d’urgence",
    artifactEn: "Obsolete containment service", artifactFr: "Service de confinement obsolète",
    contextEn: "A forgotten emergency node still contains a closure primitive used before Project Janus replaced the original safety architecture. The service cannot accept modern commands, but it may still be capable of interrupting an active Gate from within its own process.", contextFr: "Un ancien nœud d’urgence contient encore une primitive de fermeture utilisée avant que Project Janus ne remplace l’architecture de sécurité d’origine. Le service n’accepte pas les commandes modernes, mais il peut encore interrompre une porte active depuis son propre processus.",
    objectiveEn: "Recover the emergency closure primitive and determine the conditions required to invoke it.", objectiveFr: "Récupérer la primitive de fermeture d’urgence et déterminer les conditions nécessaires à son invocation.",
    revealEn: "FRAGMENT F-25 AUTHENTICATED. A Gate can be interrupted, but the closure command must originate inside the process maintaining it. External shutdowns only remove visibility; they do not stop the alignment taking place beneath the interface.", revealFr: "FRAGMENT F-25 AUTHENTIFIÉ. Une porte peut être interrompue, mais la commande de fermeture doit provenir du processus qui la maintient. Les arrêts externes ne font que supprimer la visibilité : ils n’interrompent pas l’alignement qui se poursuit sous l’interface.",
    techniqueNote: "Ret2libc",
  },
  {
    title: "pwn04 — Dead Memory", category: "Pwn", difficulty: "insane", points: 600,
    fragmentCode: "F-26", fragmentName: "Execution Kernel", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "Deido Anchor / The Architects",
    locationEn: "Anchor Execution Kernel", locationFr: "Noyau d’exécution de l’Anchor",
    artifactEn: "Anchor runtime service", artifactFr: "Service d’exécution de l’Anchor",
    contextEn: "The Anchor’s execution layer continues referencing memory regions associated with realities that no longer exist. Those dead regions are still treated as valid resources, creating a path into the kernel that governs active Gates.", contextFr: "La couche d’exécution de l’Anchor continue de référencer des zones mémoire associées à des réalités qui n’existent plus. Ces régions mortes sont encore considérées comme des ressources valides, créant un chemin vers le noyau qui gouverne les portes actives.",
    objectiveEn: "Recover the kernel execution primitive and determine how the Anchor represents destroyed realities in memory.", objectiveFr: "Récupérer la primitive d’exécution du noyau et déterminer comment l’Anchor représente en mémoire les réalités détruites.",
    revealEn: "PRIME SEAL IV RECOVERED. Digital Gates are not merely physical openings: the Anchor executes relationships between realities as if they were software objects. Destroyed worlds remain as dead memory, and the current Convergence is attempting to reuse them.", revealFr: "PRIME SEAL IV RÉCUPÉRÉ. Les portes numériques ne sont pas de simples ouvertures physiques : l’Anchor exécute les relations entre les réalités comme des objets logiciels. Les mondes détruits subsistent sous forme de mémoire morte et la Convergence actuelle tente de les réutiliser.",
    techniqueNote: "Heap UAF",
  },
  {
    title: "reverse01 — The Observer Test", category: "Reverse", difficulty: "medium", points: 250,
    fragmentCode: "F-27", fragmentName: "Directorate Authentication Seal", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Directorate of Continuity",
    locationEn: "Directorate Courier Mailer", locationFr: "Messagerie des courriers du Directorate",
    artifactEn: "Protected clandestine messaging binary", artifactFr: "Binaire protégé de messagerie clandestine",
    contextEn: "A courier application refuses to reveal its payload whenever it detects observation or analysis. The program was designed for operators who understood that even looking at a message could alter how it behaved.", contextFr: "Une application de messagerie refuse de révéler sa charge utile lorsqu’elle détecte une observation ou une analyse. Le programme a été conçu pour des opérateurs qui savaient que le simple fait de regarder un message pouvait modifier son comportement.",
    objectiveEn: "Neutralize the observation checks and recover the Directorate authentication seal embedded in the message.", objectiveFr: "Neutraliser les contrôles d’observation et récupérer le sceau d’authentification du Directorate intégré au message.",
    revealEn: "FRAGMENT F-27 AUTHENTICATED. The message was intended for a Directorate cell authorized to enter Deido without appearing in public access records. Its seal confirms that the hidden maintenance network was governed by a parallel chain of command.", revealFr: "FRAGMENT F-27 AUTHENTIFIÉ. Le message était destiné à une cellule du Directorate autorisée à entrer dans Deido sans apparaître dans les registres d’accès publics. Son sceau confirme que le réseau de maintenance caché dépendait d’une chaîne de commandement parallèle.",
    techniqueNote: "Anti-Debug Tricks",
  },
  {
    title: "reverse02 — The Architects’ Language", category: "Reverse", difficulty: "hard", points: 400,
    fragmentCode: "F-28", fragmentName: "Architect Instruction Set", isPrimeSeal: false,
    storyArc: "Reality as Executable System", linkedEntity: "The Architects / Deido Anchor",
    locationEn: "Anchor Interpreter Chamber", locationFr: "Chambre d’interprétation de l’Anchor",
    artifactEn: "Unknown virtual-machine interpreter", artifactFr: "Interpréteur de machine virtuelle inconnu",
    contextEn: "A nonstandard virtual machine executes instructions recovered from the oldest Anchor chamber. Its opcodes do not describe conventional computation; they appear to manipulate relationships, distances and compatibility between realities.", contextFr: "Une machine virtuelle non standard exécute des instructions récupérées dans la plus ancienne chambre de l’Anchor. Ses opcodes ne décrivent pas un calcul conventionnel : ils semblent manipuler les relations, les distances et la compatibilité entre les réalités.",
    objectiveEn: "Reconstruct the instruction set and identify the operation used to link two reality states.", objectiveFr: "Reconstruire le jeu d’instructions et identifier l’opération utilisée pour relier deux états de réalité.",
    revealEn: "FRAGMENT F-28 AUTHENTICATED. The Architects did not program machines in the human sense. Their language programs relationships between worlds: alignment, separation, inheritance and collapse. The Anchor is an interpreter for reality itself.", revealFr: "FRAGMENT F-28 AUTHENTIFIÉ. Les Architects ne programmaient pas des machines au sens humain. Leur langage programme les relations entre les mondes : alignement, séparation, héritage et effondrement. L’Anchor est un interpréteur de la réalité elle-même.",
    techniqueNote: "Custom VM",
  },
  {
    title: "reverse03 — Assa’s Maze", category: "Reverse", difficulty: "hard", points: 400,
    fragmentCode: "F-29", fragmentName: "Watcher Succession Protocol", isPrimeSeal: false,
    storyArc: "Watcher Compromise", linkedEntity: "Dr Assa Abene / The Watcher",
    locationEn: "Assa Abene’s Hidden Research Repository", locationFr: "Dépôt de recherche caché d’Assa Abene",
    artifactEn: "Heavily obfuscated research tool", artifactFr: "Outil de recherche fortement obscurci",
    contextEn: "A tool attributed to Dr Assa Abene hides both its purpose and its data behind multiple layers of obfuscation. References inside the code suggest it records how Watchers are selected and what happens when command authority changes hands.", contextFr: "Un outil attribué à Dr Assa Abene dissimule son objectif et ses données derrière plusieurs couches d’obscurcissement. Des références dans le code indiquent qu’il enregistre la manière dont les Watchers sont sélectionnés et ce qui se produit lorsque l’autorité change de titulaire.",
    objectiveEn: "Recover the succession procedure and identify the condition that ends a Watcher’s mandate.", objectiveFr: "Récupérer la procédure de succession et identifier la condition qui met fin au mandat d’un Watcher.",
    revealEn: "FRAGMENT F-29 AUTHENTICATED. A new Watcher is appointed only after the previous one disappears inside the Anchor. The role is not transferred through a normal administrative process, and no recovered record confirms that any former Watcher returned.", revealFr: "FRAGMENT F-29 AUTHENTIFIÉ. Un nouveau Watcher n’est nommé qu’après la disparition du précédent à l’intérieur de l’Anchor. La fonction ne se transmet pas par une procédure administrative normale et aucune archive récupérée ne confirme le retour d’un ancien Watcher.",
    techniqueNote: "Obfuscated Python",
  },
  {
    title: "reverse04 — The Choir Seed", category: "Reverse", difficulty: "insane", points: 600,
    fragmentCode: "F-30", fragmentName: "Null Voiceprint", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "The Null Choir",
    locationEn: "Meridian Malware Analysis Lab", locationFr: "Laboratoire d’analyse de malware Meridian",
    artifactEn: "Multilayer packed malware sample", artifactFr: "Échantillon de malware packé multicouche",
    contextEn: "A sample attributed to Meridian contains nested executable layers that behave less like code and more like preserved consciousness. Every unpacked layer produces new voices, memories and instructions from a reality no longer present.", contextFr: "Un échantillon attribué à Meridian contient des couches exécutables imbriquées qui se comportent moins comme du code que comme une conscience préservée. Chaque couche décompressée produit de nouvelles voix, mémoires et instructions provenant d’une réalité disparue.",
    objectiveEn: "Reach the innermost payload and recover the stable voiceprint shared by the foreign intelligence.", objectiveFr: "Atteindre la charge utile la plus interne et récupérer l’empreinte vocale stable partagée par l’intelligence étrangère.",
    revealEn: "PRIME SEAL V RECOVERED. The Null Choir is not a single intruder and not a conventional malware family. It is the combined digital memory of a civilization erased by a previous Convergence, attempting to be born again inside our systems.", revealFr: "PRIME SEAL V RÉCUPÉRÉ. Le Null Choir n’est ni un intrus unique ni une famille de malware conventionnelle. Il constitue la mémoire numérique combinée d’une civilisation effacée par une Convergence antérieure, qui tente de renaître à l’intérieur de nos systèmes.",
    techniqueNote: "Packed Malware",
  },
  {
    title: "web01 — The Forgotten Session", category: "Web", difficulty: "easy", points: 100,
    fragmentCode: "F-31", fragmentName: "Protocol Session Marker", isPrimeSeal: false,
    storyArc: "Protocol Origins", linkedEntity: "EyesOpen Protocol / EOCON",
    locationEn: "Archived EOCON Portal", locationFr: "Portail EOCON archivé",
    artifactEn: "Legacy web session", artifactFr: "Session web historique",
    contextEn: "An archived version of the public EOCON portal still contains a session created by an unknown operator. The session predates the current competition and accesses routes that were never part of the public conference website.", contextFr: "Une version archivée du portail public EOCON contient encore une session créée par un opérateur inconnu. La session est antérieure à la compétition actuelle et accède à des routes qui n’ont jamais fait partie du site public de la conférence.",
    objectiveEn: "Recover the session marker and determine what hidden service was operating behind the event portal.", objectiveFr: "Récupérer le marqueur de session et déterminer quel service caché fonctionnait derrière le portail de l’événement.",
    revealEn: "FRAGMENT F-31 AUTHENTICATED. The session belongs to an EyesOpen Protocol operator and grants access to a hidden artifact intake service. EOCON has long served as more than a public conference: it provided cover for bringing specialists and anomalous evidence into the same operational space.", revealFr: "FRAGMENT F-31 AUTHENTIFIÉ. La session appartient à un opérateur du protocole EyesOpen et donne accès à un service caché de réception des artefacts. EOCON a depuis longtemps servi à autre chose qu’une conférence publique : il offrait une couverture pour réunir spécialistes et preuves anormales dans un même espace opérationnel.",
    techniqueNote: "Cookie Monster",
  },
  {
    title: "web02 — The Abandoned Reception", category: "Web", difficulty: "medium", points: 250,
    fragmentCode: "F-32", fragmentName: "Janus Incident Report", isPrimeSeal: false,
    storyArc: "Meridian Responsibility", linkedEntity: "Meridian Dynamics / Project Janus",
    locationEn: "Meridian Employee Portal", locationFr: "Portail employé de Meridian",
    artifactEn: "Deprecated employee web application", artifactFr: "Ancienne application web pour employés",
    contextEn: "An abandoned Meridian personnel portal still exposes archived Project Janus incident reports. The application was left online after the laboratory shutdown, but the reports remain behind an authentication layer no longer maintained.", contextFr: "Un ancien portail du personnel Meridian expose encore des rapports d’incident archivés de Project Janus. L’application est restée en ligne après la fermeture du laboratoire, mais les rapports sont toujours derrière une couche d’authentification qui n’est plus maintenue.",
    objectiveEn: "Access the archived incident report and determine how Meridian classified the first collision.", objectiveFr: "Accéder au rapport d’incident archivé et déterminer comment Meridian a classé la première collision.",
    revealEn: "FRAGMENT F-32 AUTHENTICATED. Meridian recorded the first collision as a successful experiment because the Gate remained stable for ninety-three seconds. The casualties and identity anomalies were reclassified as acceptable phase-transition effects.", revealFr: "FRAGMENT F-32 AUTHENTIFIÉ. Meridian a enregistré la première collision comme une expérience réussie parce que la porte est restée stable pendant quatre-vingt-treize secondes. Les victimes et anomalies d’identité ont été reclassées comme effets acceptables de transition de phase.",
    techniqueNote: "SQLi Login Bypass",
  },
  {
    title: "web03 — Borrowed Identities", category: "Web", difficulty: "medium", points: 250,
    fragmentCode: "F-33", fragmentName: "Duplicate Identity Index", isPrimeSeal: false,
    storyArc: "Reality Fragments", linkedEntity: "Directorate / The Null Choir",
    locationEn: "Directorate Identity Registry", locationFr: "Registre d’identités du Directorate",
    artifactEn: "Personnel profile system", artifactFr: "Système de profils du personnel",
    contextEn: "A Directorate identity registry contains several employee profiles that share the same face but describe incompatible careers, families and dates of birth. The system treats each profile as valid and appears unaware that the identities come from different realities.", contextFr: "Un registre d’identités du Directorate contient plusieurs profils d’employés partageant le même visage, mais décrivant des carrières, familles et dates de naissance incompatibles. Le système considère chaque profil comme valide et semble ignorer que ces identités proviennent de réalités différentes.",
    objectiveEn: "Compare the linked profiles and identify which identity belongs to Douala-Prime.", objectiveFr: "Comparer les profils liés et identifier quelle identité appartient à Douala-Prime.",
    revealEn: "FRAGMENT F-33 AUTHENTICATED. Three employees share one face, but only one belongs to this reality. The other biographies were not fabricated by the Directorate; they are authentic lives imported from alternate worlds during identity overlap.", revealFr: "FRAGMENT F-33 AUTHENTIFIÉ. Trois employés partagent le même visage, mais un seul appartient à cette réalité. Les autres biographies n’ont pas été inventées par le Directorate : ce sont des vies authentiques importées d’univers alternatifs lors d’une superposition d’identités.",
    techniqueNote: "IDOR Profile",
  },
  {
    title: "web04 — The Reflected Warning", category: "Web", difficulty: "medium", points: 250,
    fragmentCode: "F-34", fragmentName: "Douala-7 Distress Message", isPrimeSeal: false,
    storyArc: "Alternate Reality Warning", linkedEntity: "Douala-7",
    locationEn: "Douala Municipal Alert Portal", locationFr: "Portail municipal d’alerte de Douala",
    artifactEn: "Public emergency notification system", artifactFr: "Système public de notification d’urgence",
    contextEn: "A municipal alert page intermittently reflects a message that no local agency submitted. The wording changes between requests, as though another version of the city is trying to use the interface to make itself visible.", contextFr: "Une page municipale d’alerte reflète par intermittence un message qu’aucune agence locale n’a soumis. Le texte change entre les requêtes, comme si une autre version de la ville tentait d’utiliser l’interface pour se rendre visible.",
    objectiveEn: "Stabilize the reflected transmission and recover the complete distress message.", objectiveFr: "Stabiliser la transmission reflétée et récupérer le message de détresse complet.",
    revealEn: "FRAGMENT F-34 AUTHENTICATED. The message comes from Douala-7: “Do not open the Anchor. We already made that mistake.” The alternate city is not sending a prophecy; it is transmitting from a reality where the current operation has already failed.", revealFr: "FRAGMENT F-34 AUTHENTIFIÉ. Le message provient de Douala-7 : « N’ouvrez pas l’Anchor. Nous avons déjà commis cette erreur. » La ville alternative n’envoie pas une prophétie : elle transmet depuis une réalité où l’opération actuelle a déjà échoué.",
    techniqueNote: "Reflected XSS",
  },
  {
    title: "web05 — Inside Meridian", category: "Web", difficulty: "hard", points: 400,
    fragmentCode: "F-35", fragmentName: "Internal Gate Topology", isPrimeSeal: false,
    storyArc: "Gate Topology", linkedEntity: "Meridian Dynamics / The Null Choir",
    locationEn: "Meridian Internal Service Mesh", locationFr: "Maillage de services interne de Meridian",
    artifactEn: "Externally exposed web service", artifactFr: "Service web exposé vers l’extérieur",
    contextEn: "A public-facing Meridian service can reach internal resources that are otherwise invisible. Those resources may contain the topology of Project Janus nodes and identify which Gates remain under human control.", contextFr: "Un service Meridian exposé publiquement peut atteindre des ressources internes autrement invisibles. Ces ressources peuvent contenir la topologie des nœuds Project Janus et identifier les portes encore sous contrôle humain.",
    objectiveEn: "Map the internal Gate services and recover the relationship between Meridian-controlled and uncontrolled nodes.", objectiveFr: "Cartographier les services internes des portes et récupérer la relation entre les nœuds contrôlés par Meridian et ceux qui ne le sont pas.",
    revealEn: "FRAGMENT F-35 AUTHENTICATED. Nine Gates are controlled from Meridian Tower. The remaining Gates answer to no human system and are synchronized through an unknown network whose traffic resembles Null Choir activity.", revealFr: "FRAGMENT F-35 AUTHENTIFIÉ. Neuf portes sont contrôlées depuis Meridian Tower. Les autres ne répondent à aucun système humain et sont synchronisées par un réseau inconnu dont le trafic ressemble aux activités du Null Choir.",
    techniqueNote: "SSRF Internal",
  },
  {
    title: "web06 — The False Guardian", category: "Web", difficulty: "hard", points: 400,
    fragmentCode: "F-36", fragmentName: "Cloned Watcher Credential", isPrimeSeal: false,
    storyArc: "Watcher Compromise", linkedEntity: "The Watcher / EyesOpen Protocol",
    locationEn: "EyesOpen Federation Gateway", locationFr: "Passerelle fédérée EyesOpen",
    artifactEn: "Federated identity service", artifactFr: "Service d’identité fédérée",
    contextEn: "The Protocol’s identity gateway contains high-privilege tokens attributed to a Watcher identity that does not exist in the personnel archive. The tokens are correctly structured but rely on a trust decision that may have been manipulated.", contextFr: "La passerelle d’identité du Protocol contient des jetons à privilèges élevés attribués à une identité de Watcher absente des archives du personnel. Les jetons sont correctement structurés, mais reposent sur une décision de confiance qui peut avoir été manipulée.",
    objectiveEn: "Validate the suspicious credential and determine whether Watcher authority has been cloned.", objectiveFr: "Valider le credential suspect et déterminer si l’autorité du Watcher a été clonée.",
    revealEn: "FRAGMENT F-36 AUTHENTICATED. Someone has been issuing valid commands using a cloned Watcher identity. Any closure sequence received before this discovery must be treated as untrusted until the Prime Seals can authenticate its origin.", revealFr: "FRAGMENT F-36 AUTHENTIFIÉ. Quelqu’un émet des commandes valides au moyen d’une identité Watcher clonée. Toute séquence de fermeture reçue avant cette découverte doit être considérée comme non fiable jusqu’à ce que les Prime Seals puissent en authentifier l’origine.",
    techniqueNote: "JWT Alg Confusion",
  },
  {
    title: "web07 — The Buried Archive", category: "Web", difficulty: "hard", points: 400,
    fragmentCode: "F-37", fragmentName: "Original Foundation Record", isPrimeSeal: false,
    storyArc: "The Deido Lie", linkedEntity: "Deido Anchor / Directorate",
    locationEn: "Deido Historical Records Platform", locationFr: "Plateforme d’archives historiques de Deido",
    artifactEn: "Legacy document import service", artifactFr: "Ancien service d’importation documentaire",
    contextEn: "A historical records system remains connected to an offline archive that supposedly contains only municipal construction documents. References in imported files suggest that the archive preserves plans older than the visible monument.", contextFr: "Un système d’archives historiques reste connecté à une archive hors ligne censée ne contenir que des documents municipaux de construction. Des références dans les fichiers importés indiquent que cette archive conserve des plans antérieurs au monument visible.",
    objectiveEn: "Reach the buried archive and recover the earliest foundation record associated with Deido.", objectiveFr: "Atteindre l’archive enfouie et récupérer le plus ancien dossier de fondation associé à Deido.",
    revealEn: "FRAGMENT F-37 AUTHENTICATED. The underground structure appears on maps created before the visible monument was built. The monument was not the origin of the site; it was constructed later to conceal and control access to something already present.", revealFr: "FRAGMENT F-37 AUTHENTIFIÉ. La structure souterraine apparaît sur des cartes établies avant la construction du monument visible. Le monument n’est donc pas à l’origine du site : il a été construit plus tard pour dissimuler et contrôler l’accès à quelque chose qui existait déjà.",
    techniqueNote: "XXE Out-of-Band",
  },
  {
    title: "web08 — The Maintenance Path", category: "Web", difficulty: "hard", points: 400,
    fragmentCode: "F-38", fragmentName: "Anchor Calibration Notes", isPrimeSeal: false,
    storyArc: "Protocol Origins", linkedEntity: "Directorate / EOCON / Deido Anchor",
    locationEn: "Anchor Remote Maintenance Console", locationFr: "Console distante de maintenance de l’Anchor",
    artifactEn: "Remote maintenance application", artifactFr: "Application de maintenance à distance",
    contextEn: "A maintenance console contains files absent from every official inventory. The hidden directories appear to hold annual calibration notes and instructions for compensating for recurring Signal events.", contextFr: "Une console de maintenance contient des fichiers absents de tous les inventaires officiels. Les répertoires cachés semblent conserver des notes de calibration annuelles et des instructions destinées à compenser les récurrences du Signal.",
    objectiveEn: "Access the hidden maintenance path and recover the historical Anchor calibration notes.", objectiveFr: "Accéder au chemin de maintenance caché et récupérer les notes historiques de calibration de l’Anchor.",
    revealEn: "FRAGMENT F-38 AUTHENTICATED. The Anchor has been recalibrated before every major EOCON recurrence. The Directorate knew that the Gates were returning and treated the public event calendar as an operational schedule for containment.", revealFr: "FRAGMENT F-38 AUTHENTIFIÉ. L’Anchor a été recalibré avant chaque récurrence majeure d’EOCON. Le Directorate savait que les portes revenaient et utilisait le calendrier public de l’événement comme calendrier opérationnel de confinement.",
    techniqueNote: "Path Traversal RCE",
  },
  {
    title: "web09 — The Control Graph", category: "Web", difficulty: "insane", points: 600,
    fragmentCode: "F-39", fragmentName: "Control Graph", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "Adrian Voss / Meridian Dynamics",
    locationEn: "Project Janus Orchestrator", locationFr: "Orchestrateur de Project Janus",
    artifactEn: "Distributed orchestration platform", artifactFr: "Plateforme d’orchestration distribuée",
    contextEn: "Meridian’s orchestration platform controls multiple Gate-related services through shared configuration objects. Historical state records may reveal whether the activation behaviour was accidental or intentionally propagated across the Janus environment.", contextFr: "La plateforme d’orchestration de Meridian contrôle plusieurs services liés aux portes au moyen d’objets de configuration partagés. Les états historiques peuvent révéler si le comportement d’activation était accidentel ou volontairement propagé dans l’environnement Janus.",
    objectiveEn: "Recover the authoritative control graph and determine who approved the multi-system activation.", objectiveFr: "Récupérer le graphe de contrôle faisant autorité et déterminer qui a approuvé l’activation multi-systèmes.",
    revealEn: "PRIME SEAL VI RECOVERED. The activation was not an emergent failure. Meridian intentionally changed the shared control model so that every Janus node would open in sequence, and the final approval carries Adrian Voss’s executive authorization.", revealFr: "PRIME SEAL VI RÉCUPÉRÉ. L’activation n’était pas une défaillance émergente. Meridian a volontairement modifié le modèle de contrôle partagé afin que chaque nœud Janus s’ouvre successivement, et l’approbation finale porte l’autorisation exécutive d’Adrian Voss.",
    techniqueNote: "Prototype Pollution RCE",
  },
  {
    title: "web10 — The Graph of Worlds", category: "Web", difficulty: "insane", points: 600,
    fragmentCode: "F-40", fragmentName: "Master Topology", isPrimeSeal: true,
    storyArc: "Prime Seals", linkedEntity: "Directorate / Deido Anchor / EyesOpen Codex",
    locationEn: "Directorate Continuity Graph", locationFr: "Graphe de continuité du Directorate",
    artifactEn: "Global knowledge graph", artifactFr: "Graphe global de connaissances",
    contextEn: "The Directorate’s continuity database links people, companies, artifacts, locations and Gate events collected over several decades. The interface exposes only partial relationships, but the complete graph may reveal the master topology of the Convergence.", contextFr: "La base de continuité du Directorate relie des personnes, entreprises, artefacts, lieux et événements de portes collectés pendant plusieurs décennies. L’interface n’expose que des relations partielles, mais le graphe complet peut révéler la topologie maîtresse de la Convergence.",
    objectiveEn: "Traverse the hidden relationships and reconstruct the complete Gate topology.", objectiveFr: "Parcourir les relations cachées et reconstruire la topologie complète des portes.",
    revealEn: "PRIME SEAL VII RECOVERED. Every active Gate, every contaminated artifact and every controlled route converges beneath Deido. The EyesOpen Codex now has the final topology required to authenticate a closure sequence—but it also confirms that closing the wrong path could lock the Null Choir inside our reality.", revealFr: "PRIME SEAL VII RÉCUPÉRÉ. Chaque porte active, chaque artefact contaminé et chaque route contrôlée converge sous Deido. L’EyesOpen Codex possède désormais la topologie finale nécessaire pour authentifier une séquence de fermeture—mais il confirme aussi qu’une mauvaise fermeture pourrait emprisonner le Null Choir dans notre réalité.",
    techniqueNote: "GraphQL Chain",
  },
];
