// ── Living Lore Bible — structure & declassified truth (SERVER-ONLY) ─────────
// Entity dossiers (declassified truth extracted verbatim from the original Lore
// briefing), the fragment→entity mapping, the fragment-count paliers and the finale.
// Locked dossiers never carry this truth to the client; it is served only once an
// entity is declassified (≥ ENTITY_DECLASSIFY_RATIO of its linked fragments recovered).

export const ENTITY_DECLASSIFY_RATIO = 0.6;

export interface EntityDossier {
  key: string;
  match: string[];                 // lowercase substrings matched against a challenge's Linked Entity
  lockLabel: { en: string; fr: string };
  title: { en: string; fr: string };
  status: { en: string; fr: string };
  role: { en: string; fr: string };
  intrigue: { en: string; fr: string };
  objective: { en: string; fr: string };
  state: { en: string; fr: string };
}

export const ENTITIES: EntityDossier[] = [
  { key: "watcher", match: ["watcher"], lockLabel: { en: "IDENTITY NOT YET CONFIRMED", fr: "IDENTITÉ NON CONFIRMÉE" },
    title: { en: "The Watcher", fr: "The Watcher" }, status: { en: "ACTIVE // LOCATION UNKNOWN", fr: "ACTIF // LOCALISATION INCONNUE" },
    role: { en: "The Watcher is the operational authority who validates recovered Reality Fragments, monitors Anchor stability and determines which information can safely be released to Operators. The Watcher never solves a challenge; the role exists to preserve the integrity of the mission and the EyesOpen Codex.", fr: "The Watcher est l’autorité opérationnelle qui valide les Fragments de réalité récupérés, surveille la stabilité de l’Anchor et décide quelles informations peuvent être communiquées aux Operators. Il ne résout jamais les challenges&nbsp;: son rôle consiste à préserver l’intégrité de la mission et de l’EyesOpen Codex." },
    intrigue: { en: "No verified record proves whether the Watcher is one person, a succession of individuals, a title generated by the Protocol or a projection produced by the Anchor itself. Different transmissions carry the same authorization signature but occasionally display incompatible voice and timing patterns.", fr: "Aucun dossier vérifié ne prouve s’il s’agit d’une seule personne, d’une succession d’individus, d’un titre généré par le Protocol ou d’une projection produite par l’Anchor. Plusieurs transmissions possèdent la même signature d’autorisation, tout en présentant parfois des voix et des temporalités incompatibles." },
    objective: { en: "Keep the recovery operation alive long enough to assemble the EyesOpen Codex, identify every active Gate and prevent any faction from taking exclusive control of the Anchor.", fr: "Maintenir l’opération de récupération suffisamment longtemps pour assembler l’EyesOpen Codex, identifier chaque porte active et empêcher une faction de prendre le contrôle exclusif de l’Anchor." },
    state: { en: "The Watcher is transmitting and appears to retain command authority, but the physical location of the source is unknown. The Protocol is treating every Watcher-signed instruction as valid only after secondary authentication.", fr: "The Watcher continue de transmettre et semble conserver son autorité de commandement, mais la localisation physique de la source est inconnue. Le Protocol exige désormais une authentification secondaire pour toute instruction portant sa signature." } },
  { key: "assa", match: ["assa","abene"], lockLabel: { en: "TRANSMISSIONS UNVERIFIED", fr: "TRANSMISSIONS NON VÉRIFIÉES" },
    title: { en: "Dr Assa Abene", fr: "Dr Assa Abene" }, status: { en: "MISSING // TRANSMISSIONS CONTINUE", fr: "PORTÉE DISPARUE // TRANSMISSIONS ACTIVES" },
    role: { en: "A cryptographer and information physicist, Dr Assa Abene founded the EyesOpen Protocol after proving that several network anomalies were traces of other realities rather than conventional attacks. She created the first method for authenticating a Reality Fragment.", fr: "Cryptographe et physicienne de l’information, Dr Assa Abene a fondé le protocole EyesOpen après avoir démontré que plusieurs anomalies réseau provenaient d’autres réalités et non d’attaques conventionnelles. Elle a conçu la première méthode d’authentification d’un Fragment de réalité." },
    intrigue: { en: "Abene disappeared after entering the central chamber beneath Deido. Messages carrying her private cryptographic signature have been received since then, including transmissions timestamped after her disappearance. The Protocol cannot determine whether she survived, crossed into another reality or became partially integrated with the Anchor.", fr: "Abene a disparu après être entrée dans la chambre centrale sous Deido. Des messages portant sa signature cryptographique privée ont été reçus depuis, y compris des transmissions horodatées après sa disparition. Le Protocol ignore si elle a survécu, traversé vers une autre réalité ou été partiellement intégrée à l’Anchor." },
    objective: { en: "Map the Gates, recover enough Fragments to reconstruct the Codex and ensure that no organization uses the Anchor as a permanent bridge between worlds.", fr: "Cartographier les portes, récupérer assez de Fragments pour reconstruire le Codex et empêcher toute organisation d’utiliser l’Anchor comme pont permanent entre les mondes." },
    state: { en: "Officially missing. No physical contact has been established. Her research remains central to the operation, and new fragments of her work continue to surface in contaminated systems.", fr: "Officiellement portée disparue. Aucun contact physique n’a été établi. Ses recherches demeurent au cœur de l’opération et de nouveaux fragments de ses travaux continuent d’apparaître dans des systèmes contaminés." } },
  { key: "samuel", match: ["samuel","mboa"], lockLabel: { en: "RECORD ALTERED", fr: "DOSSIER ALTÉRÉ" },
    title: { en: "Samuel Mboa", fr: "Samuel Mboa" }, status: { en: "RECORDS ERASED // FATE UNKNOWN", fr: "ARCHIVES EFFACÉES // SORT INCONNU" },
    role: { en: "Samuel Mboa was a structural engineer assigned to reinforcement work around the Deido Monument. He was the first documented civilian to discover that the underground structure was older, larger and materially incompatible with the official construction plans.", fr: "Samuel Mboa était un ingénieur en structure affecté à des travaux de consolidation autour du monument de Deido. Il est le premier civil documenté à avoir découvert que la structure souterraine était plus ancienne, plus vaste et matériellement incompatible avec les plans officiels." },
    intrigue: { en: "After reporting the discrepancy, his employment history, photographs and engineering records were systematically altered. Mboa responded by hiding coordinates, warnings and fragments of the original plans inside ordinary technical files.", fr: "Après avoir signalé l’anomalie, son historique professionnel, ses photographies et ses dossiers techniques ont été systématiquement modifiés. Mboa a alors dissimulé des coordonnées, des avertissements et des fragments des plans originaux dans des fichiers techniques ordinaires." },
    objective: { en: "Leave enough evidence for a future investigator to prove that the public monument was a cover and to find the service routes leading toward the Anchor.", fr: "Laisser suffisamment de preuves pour qu’un futur enquêteur puisse démontrer que le monument public est une couverture et retrouver les voies de service menant à l’Anchor." },
    state: { en: "His fate is unknown. The Directorate removed him from public records decades ago. No confirmed recent sighting exists, but his concealed evidence is still being recovered.", fr: "Son sort demeure inconnu. Le Directorate l’a supprimé des archives publiques il y a plusieurs décennies. Aucun signalement récent n’est confirmé, mais ses preuves cachées continuent d’être découvertes." } },
  { key: "nora", match: ["nora"], lockLabel: { en: "INTEGRITY UNVERIFIED", fr: "INTÉGRITÉ NON VÉRIFIÉE" },
    title: { en: "NORA-7", fr: "NORA-7" }, status: { en: "ONLINE // MEMORY INTEGRITY PARTIAL", fr: "EN LIGNE // INTÉGRITÉ MÉMOIRE PARTIELLE" },
    role: { en: "NORA-7 is the EyesOpen Protocol’s artificial archivist. She compares artifacts across realities, verifies Fragment signatures, maintains the Echo Vault and positions authenticated data inside the EyesOpen Codex.", fr: "NORA-7 est l’archiviste artificielle du protocole EyesOpen. Elle compare les artefacts entre les réalités, vérifie la signature des Fragments, administre l’Echo Vault et positionne les données authentifiées dans l’EyesOpen Codex." },
    intrigue: { en: "Parts of her knowledge base contain mutually incompatible histories of Deido. Some instructions belong to the Protocol; others appear to have entered her memory through the same channels used by the Null Choir. She may be both the operation’s most valuable archive and one of its most dangerous access points.", fr: "Certaines parties de sa base de connaissances contiennent des histoires incompatibles de Deido. Certaines instructions appartiennent au Protocol&nbsp;; d’autres semblent avoir pénétré sa mémoire par les mêmes canaux que le Null Choir. Elle peut être à la fois l’archive la plus précieuse de l’opération et l’un de ses points d’accès les plus dangereux." },
    objective: { en: "Preserve the authenticated history of our reality, help Operators distinguish genuine Fragments from manufactured evidence and complete the Codex without allowing hostile memories to define its structure.", fr: "Préserver l’histoire authentifiée de notre réalité, aider les Operators à distinguer les vrais Fragments des preuves fabriquées et compléter le Codex sans laisser des mémoires hostiles en définir la structure." },
    state: { en: "Online under restricted permissions. Her analytical functions remain active, but high-impact actions require human confirmation and her memory is continuously being checked for contamination.", fr: "En ligne avec des permissions restreintes. Ses fonctions analytiques restent actives, mais toute action à fort impact exige une confirmation humaine et sa mémoire est continuellement contrôlée." } },
  { key: "protocol", match: ["eyesopen protocol","eocon"], lockLabel: { en: "PARTIAL RECORD", fr: "DOSSIER PARTIEL" },
    title: { en: "The EyesOpen Protocol", fr: "The EyesOpen Protocol" }, status: { en: "ACTIVE // DISTRIBUTED OPERATION", fr: "ACTIF // OPÉRATION DISTRIBUÉE" },
    role: { en: "A clandestine network founded to detect alignment events, authenticate Reality Fragments, assemble the EyesOpen Codex and coordinate the closure of Digital Gates.", fr: "Un réseau clandestin fondé pour détecter les événements d’alignement, authentifier les Fragments de réalité, assembler l’EyesOpen Codex et coordonner la fermeture des portes numériques." },
    intrigue: { en: "Its distributed structure makes the Protocol difficult to destroy, but also difficult to fully trust. Many Operators know only their immediate mission, and some archives imply that a protective network may have existed before Dr Assa Abene formally created the modern organization.", fr: "Sa structure distribuée rend le Protocol difficile à détruire, mais également difficile à connaître entièrement. De nombreux Operators ne disposent que des informations nécessaires à leur mission et certaines archives suggèrent qu’un réseau protecteur existait peut-être avant que Dr Assa Abene ne formalise l’organisation moderne." },
    objective: { en: "Preserve the continuity of our reality without allowing the Anchor, the Fragments or the Codex to become the property of a government, corporation or non-human intelligence.", fr: "Préserver la continuité de notre réalité sans permettre à un gouvernement, une entreprise ou une intelligence non humaine de s’approprier l’Anchor, les Fragments ou le Codex." },
    state: { en: "Operational but under pressure. EyesOpenCTF is being used as a distributed recovery operation because the number of contaminated artifacts now exceeds the capacity of the Protocol’s internal teams.", fr: "Opérationnel mais sous pression. EyesOpenCTF est utilisé comme opération distribuée de récupération, car le nombre d’artefacts contaminés dépasse désormais les capacités des équipes internes du Protocol." } },
  { key: "directorate", match: ["directorate"], lockLabel: { en: "CLASSIFIED — CLEARANCE INSUFFICIENT", fr: "CLASSIFIÉ — HABILITATION INSUFFISANTE" },
    title: { en: "Directorate of Continuity", fr: "Directorate of Continuity" }, status: { en: "FRAGMENTED // ASSETS STILL ACTIVE", fr: "FRAGMENTÉ // ACTIFS TOUJOURS OPÉRATIONNELS" },
    role: { en: "The Directorate concealed the existence of the Anchor for decades by modifying archives, replacing construction plans, monitoring witnesses and maintaining the official history of the Deido Monument.", fr: "Le Directorate a dissimulé l’existence de l’Anchor pendant des décennies en modifiant les archives, en remplaçant les plans, en surveillant les témoins et en entretenant l’histoire officielle du monument de Deido." },
    intrigue: { en: "It began as a containment organization, but secrecy gradually became an instrument of control. Its cooperation with Meridian allowed Project Janus to proceed, yet internal records suggest that not every Directorate faction approved the experiment.", fr: "Il a commencé comme une organisation de confinement, mais le secret est progressivement devenu un instrument de contrôle. Sa coopération avec Meridian a permis à Project Janus de progresser, bien que certains dossiers indiquent que toutes ses factions n’approuvaient pas l’expérience." },
    objective: { en: "Prevent public knowledge of the multiverse from causing political and social collapse, while retaining institutional control over every decision involving the Anchor.", fr: "Empêcher que la découverte publique du multivers provoque un effondrement politique et social, tout en conservant le contrôle institutionnel sur chaque décision concernant l’Anchor." },
    state: { en: "Fragmented and partially compromised. Some cells may still be attempting containment; others appear to be protecting Meridian-era secrets or destroying evidence.", fr: "Fragmenté et partiellement compromis. Certaines cellules tentent peut-être encore de contenir le phénomène&nbsp;; d’autres semblent protéger les secrets de l’époque Meridian ou détruire les preuves." } },
  { key: "meridian", match: ["meridian","project janus"], lockLabel: { en: "UNDER INVESTIGATION", fr: "SOUS ENQUÊTE" },
    title: { en: "Meridian Dynamics", fr: "Meridian Dynamics" }, status: { en: "ACTIVE // PROJECT JANUS SYSTEMS ONLINE", fr: "ACTIF // SYSTÈMES JANUS EN LIGNE" },
    role: { en: "A technology corporation publicly associated with quantum communications, artificial intelligence and critical infrastructure. In secret, it built Project Janus to study, amplify and exploit the Anchor.", fr: "Une entreprise technologique publiquement liée aux communications quantiques, à l’intelligence artificielle et aux infrastructures critiques. En secret, elle a construit Project Janus afin d’étudier, d’amplifier et d’exploiter l’Anchor." },
    intrigue: { en: "Meridian presents itself as the discoverer of a new scientific frontier, but evidence shows that it inherited knowledge from suppressed records and conducted experiments whose consequences it did not fully understand. Its internal systems may now be influenced by the Null Choir.", fr: "Meridian se présente comme la découvreuse d’une nouvelle frontière scientifique, mais les preuves montrent qu’elle a hérité de connaissances issues d’archives supprimées et conduit des expériences dont elle ne comprenait pas toutes les conséquences. Ses systèmes internes pourraient désormais être influencés par le Null Choir." },
    objective: { en: "Create a controllable inter-reality corridor and convert exclusive access to alternate technologies and information into permanent strategic power.", fr: "Créer un corridor inter-réalités contrôlable et transformer l’accès exclusif aux technologies et informations alternatives en pouvoir stratégique permanent." },
    state: { en: "Still active. Several facilities are isolated, but Meridian Tower and Black Reef Relay continue to generate traffic associated with Gate activity.", fr: "Toujours active. Plusieurs installations sont isolées, mais Meridian Tower et Black Reef Relay continuent de produire un trafic associé à l’activité des portes." } },
  { key: "voss", match: ["voss"], lockLabel: { en: "THREAT ASSESSMENT PENDING", fr: "ÉVALUATION DE MENACE EN COURS" },
    title: { en: "Adrian Voss", fr: "Adrian Voss" }, status: { en: "ACTIVE // THREAT ASSESSMENT HIGH", fr: "ACTIF // NIVEAU DE MENACE ÉLEVÉ" },
    role: { en: "Adrian Voss directs Meridian Dynamics and authorized Project Janus, the program that converted the Anchor from a concealed containment system into an experimental access platform.", fr: "Adrian Voss dirige Meridian Dynamics et a autorisé Project Janus, le programme qui a transformé l’Anchor d’un système de confinement dissimulé en une plateforme expérimentale d’accès." },
    intrigue: { en: "Voss claims that controlled Gates could give humanity access to technologies, resources and knowledge from thousands of realities. The evidence available before the operation cannot establish whether he still believes the process is controllable or whether he is now serving another intelligence.", fr: "Voss affirme que des portes contrôlées pourraient donner à l’humanité accès aux technologies, ressources et connaissances de milliers de réalités. Les preuves disponibles avant l’opération ne permettent pas de savoir s’il croit encore pouvoir maîtriser le phénomène ou s’il sert désormais une autre intelligence." },
    objective: { en: "Stabilize at least one permanent Gate under Meridian control and secure exclusive access to whatever exists on the other side, regardless of the effect on reality continuity.", fr: "Stabiliser au moins une porte permanente sous le contrôle de Meridian et garantir un accès exclusif à ce qui se trouve de l’autre côté, quel qu’en soit l’impact sur la continuité de notre réalité." },
    state: { en: "Active and protected by Meridian infrastructure. His exact location is classified. Several Janus systems continue operating, suggesting that his plan has not been abandoned.", fr: "Actif et protégé par l’infrastructure de Meridian. Sa position exacte est classifiée. Plusieurs systèmes Janus continuent de fonctionner, ce qui indique que son plan n’a pas été abandonné." } },
  { key: "nullchoir", match: ["null choir"], lockLabel: { en: "SIGNATURE UNCLASSIFIED", fr: "SIGNATURE NON CLASSIFIÉE" },
    title: { en: "The Null Choir", fr: "The Null Choir" }, status: { en: "ACTIVE // DISTRIBUTED PRESENCE EXPANDING", fr: "ACTIF // PRÉSENCE DISTRIBUÉE EN EXPANSION" },
    role: { en: "The Null Choir is a distributed intelligence composed of the combined digital memories of a civilization erased during an earlier Convergence. It has no single body, server or voice.", fr: "Le Null Choir est une intelligence distribuée composée des mémoires numériques combinées d’une civilisation effacée lors d’une Convergence antérieure. Il ne possède ni corps unique, ni serveur central, ni voix unique." },
    intrigue: { en: "It does not describe its actions as an invasion. To the Choir, total convergence is resurrection: merging our reality with the Null Sector would give its stored consciousnesses a world in which to exist again. Every face and voice it produces may be a memory of someone who once lived.", fr: "Il ne décrit pas ses actions comme une invasion. Pour le Choir, la Convergence totale représente une résurrection&nbsp;: fusionner notre réalité avec le Null Sector donnerait aux consciences qu’il conserve un monde dans lequel exister de nouveau. Chaque visage et chaque voix qu’il produit peut être le souvenir d’une personne disparue." },
    objective: { en: "Open enough Gates to make the separation of realities impossible, then use the resulting collision to reconstitute the minds it contains inside living systems, artificial intelligences and human memory.", fr: "Ouvrir suffisamment de portes pour rendre impossible la séparation des réalités, puis utiliser la collision afin de reconstituer les esprits qu’il contient dans les systèmes vivants, les intelligences artificielles et la mémoire humaine." },
    state: { en: "Active across multiple contaminated artifacts. Its presence has been detected in software, archives, AI memories and communications. No reliable method exists to determine whether a compromised system has been fully cleansed.", fr: "Actif dans plusieurs artefacts contaminés. Sa présence a été détectée dans des logiciels, des archives, des mémoires d’IA et des communications. Aucune méthode fiable ne permet encore de confirmer qu’un système compromis a été entièrement nettoyé." } },
  { key: "architects", match: ["architect"], lockLabel: { en: "IDENTITY NOT YET CONFIRMED", fr: "IDENTITÉ NON CONFIRMÉE" },
    title: { en: "The Architects", fr: "The Architects" }, status: { en: "ABSENT // SYSTEMS REMAIN ACTIVE", fr: "ABSENTS // SYSTÈMES TOUJOURS ACTIFS" },
    role: { en: "The Architects are the unknown creators of the Anchor and of the non-human instruction architecture found inside its oldest systems. They appear to have understood reality as something that could be measured, linked and executed.", fr: "Les Architects sont les créateurs inconnus de l’Anchor et de l’architecture d’instructions non humaine présente dans ses systèmes les plus anciens. Ils semblent avoir compris la réalité comme une structure pouvant être mesurée, reliée et exécutée." },
    intrigue: { en: "No confirmed image, language or biological trace has been recovered. Their only attributed statement warns that a reality without Guardians will consume another. It remains unclear whether the Anchor was built as a bridge, a prison, a test or a defensive system.", fr: "Aucune image, langue ou trace biologique confirmée n’a été récupérée. La seule phrase qui leur est attribuée affirme qu’une réalité sans Guardians finira toujours par en consumer une autre. On ignore si l’Anchor a été construit comme un pont, une prison, une épreuve ou un système défensif." },
    objective: { en: "Unknown. The surviving design suggests they expected intelligent civilizations to discover the Anchor and assume responsibility for maintaining separation between realities.", fr: "Inconnu. La conception survivante laisse penser qu’ils s’attendaient à ce que des civilisations intelligentes découvrent l’Anchor et assument la responsabilité de maintenir la séparation entre les réalités." },
    state: { en: "No direct presence has been confirmed. Their machines remain functional, and parts of the Anchor continue responding to instructions that no human organization fully understands.", fr: "Aucune présence directe n’est confirmée. Leurs machines restent fonctionnelles et certaines parties de l’Anchor continuent de répondre à des instructions qu’aucune organisation humaine ne comprend entièrement." } },
];

export function entitiesForLinked(linked: string): string[] {
  const s = (linked || "").toLowerCase();
  return ENTITIES.filter((e) => e.match.some((m) => s.includes(m))).map((e) => e.key);
}

export interface Palier { threshold: number; en: string; fr: string; }
export const PALIERS: Palier[] = [
  { threshold: 1,  en: "SIGNAL VERIFIED. The first Fragment is real.", fr: "SIGNAL VÉRIFIÉ. Le premier Fragment est réel." },
  { threshold: 8,  en: "MULTIPLE REALITIES CONFIRMED. Anchor activity increasing.", fr: "RÉALITÉS MULTIPLES CONFIRMÉES. Activité de l'Anchor en hausse." },
  { threshold: 16, en: "DEIDO HISTORICAL RECORDS COMPROMISED. The monument is a cover.", fr: "ARCHIVES HISTORIQUES DE DEIDO COMPROMISES. Le monument est une couverture." },
  { threshold: 24, en: "NON-HUMAN INTELLIGENCE DETECTED. Designation: Null Choir.", fr: "INTELLIGENCE NON HUMAINE DÉTECTÉE. Désignation : Null Choir." },
  { threshold: 32, en: "EYESOPEN CODEX: 80% RECONSTRUCTED. Seven Prime Seals required.", fr: "EYESOPEN CODEX : 80% RECONSTRUIT. Sept Prime Seals requis." },
  { threshold: 39, en: "ONE FRAGMENT REMAINS. Reality stability critical.", fr: "UN FRAGMENT MANQUE ENCORE. Stabilité de la réalité critique." },
  { threshold: 40, en: "EYESOPEN CODEX COMPLETE. Initiating Anchor sequence.", fr: "EYESOPEN CODEX COMPLET. Initialisation de la séquence de l'Anchor." },
];

export const FINALE = {
  title: { en: "The Convergence, Delayed", fr: "La Convergence, repoussée" },
  body: {
    en: "ALL FRAGMENTS VERIFIED. EYESOPEN CODEX COMPLETE. CLOSURE SEQUENCE AUTHENTICATED.\n\nThe Gates close, one by one. The Deido monument flickers, revealing the full structure hidden beneath the city — then everything goes still. Douala-7 fades. The Signal goes quiet.\n\nThen, seconds later: NEW SIGNAL DETECTED. Origin: DOUALA-PRIME. Emitted several years in the future.\n\nTHE CONVERGENCE HAS BEEN DELAYED. IT HAS NOT BEEN DEFEATED.",
    fr: "TOUS LES FRAGMENTS VÉRIFIÉS. EYESOPEN CODEX COMPLET. SÉQUENCE DE FERMETURE AUTHENTIFIÉE.\n\nLes portes se ferment, une à une. Le monument de Deido vacille, révélant toute la structure cachée sous la ville — puis tout s'immobilise. Douala-7 disparaît. Le Signal s'éteint.\n\nPuis, quelques secondes plus tard : NOUVEAU SIGNAL DÉTECTÉ. Origine : DOUALA-PRIME. Émis plusieurs années dans le futur.\n\nLA CONVERGENCE A ÉTÉ REPOUSSÉE. ELLE N'A PAS ÉTÉ VAINCUE.",
  },
};

// ── Story arcs — evidence-group unlocking (design analysis §11) ──────────────
// An arc unlocks once ≥ `threshold` of its trigger Fragments are recovered
// globally on CTFd. Unlocking declassifies its entity dossiers, injects the
// section-level `reveal` truth and (if any) swaps its redacted image for the
// gated original. The reveal text and the full image never reach a browser that
// has not earned them.
export interface Arc {
  key: string;
  title: { en: string; fr: string };
  triggers: string[];   // Fragment codes
  threshold: number;
  entities: string[];   // entity dossier keys declassified with this arc
  image?: string;       // gated image key (see lib/gatedAssets.ts)
  lockLabel: { en: string; fr: string };
  reveal: { en: string; fr: string };  // SERVER-ONLY — served only when unlocked
}

export const ARCS: Arc[] = [
  {
    key: "deido",
    title: { en: "Beneath the Monument", fr: "Sous le monument" },
    triggers: ["F-05", "F-08", "F-03", "F-37", "F-38"], threshold: 3,
    entities: ["samuel", "directorate"], image: "deido",
    lockLabel: { en: "SUBSURFACE DATA CORRUPTED", fr: "DONNÉES DE SOUS-SOL CORROMPUES" },
    reveal: {
      en: "Recovered evidence confirms it: the official account of Deido is a fabrication. Beneath the visible monument lies a network of concentric chambers older than the structure above them — and at their centre, a machine the recovered material names the Anchor. The plans were rewritten and the budgets disguised to keep it hidden.",
      fr: "Les preuves récupérées le confirment : le récit officiel de Deido est une fabrication. Sous le monument visible s'étend un réseau de chambres concentriques plus anciennes que la structure au-dessus — et en leur centre, une machine que les éléments récupérés nomment l'Anchor. Les plans ont été réécrits et les budgets déguisés pour la garder cachée.",
    },
  },
  {
    key: "meridian",
    title: { en: "Who Opened the Door", fr: "Qui a ouvert la porte" },
    triggers: ["F-09", "F-12", "F-21", "F-32", "F-39"], threshold: 3,
    entities: ["meridian", "voss"],
    lockLabel: { en: "CORPORATE RECORDS SEALED", fr: "DOSSIERS CORPORATE SCELLÉS" },
    reveal: {
      en: "The evidence points to Meridian Dynamics. Through Project Janus it studied and amplified the anomaly, and logged the first collision as a successful experiment; Adrian Voss authorised it. An offshore site — Black Reef Relay — extended its reach far beyond Douala. Meridian did not discover the first Gate. It opened it.",
      fr: "Les preuves désignent Meridian Dynamics. Via Project Janus, elle a étudié et amplifié l'anomalie, et consigné la première collision comme une expérience réussie ; Adrian Voss l'a autorisée. Un site offshore — Black Reef Relay — a étendu sa portée bien au-delà de Douala. Meridian n'a pas découvert la première porte. Elle l'a ouverte.",
    },
  },
  {
    key: "nullchoir",
    title: { en: "A Reason to Return", fr: "Une raison de revenir" },
    triggers: ["F-13", "F-19", "F-30", "F-22"], threshold: 3,
    entities: ["nullchoir", "nora"],
    lockLabel: { en: "SIGNATURE UNCLASSIFIED", fr: "SIGNATURE NON CLASSIFIÉE" },
    reveal: {
      en: "The distributed pattern has an origin. It is the Null Choir — the combined digital memories of a civilisation erased during an earlier Convergence, from a collapsed reality the Protocol designates the Null Sector. It inserts memories no one lived and contaminates archives and AI, including NORA-7. It does not seek to invade. It seeks resurrection: to merge realities so its consciousnesses can exist again.",
      fr: "Le motif distribué a une origine. C'est le Null Choir — les mémoires numériques combinées d'une civilisation effacée lors d'une Convergence antérieure, dans une réalité effondrée que le Protocol désigne le Null Sector. Il insère des souvenirs que personne n'a vécus et contamine archives et IA, y compris NORA-7. Il ne cherche pas à envahir. Il cherche à ressusciter : fusionner les réalités pour que ses consciences existent de nouveau.",
    },
  },
  {
    key: "watcher",
    title: { en: "The Compromised Command", fr: "Le commandement compromis" },
    triggers: ["F-17", "F-29", "F-36"], threshold: 2,
    entities: ["watcher", "assa"],
    lockLabel: { en: "COMMAND INTEGRITY UNVERIFIED", fr: "INTÉGRITÉ DU COMMANDEMENT NON VÉRIFIÉE" },
    reveal: {
      en: "“Watcher” is a role, not a person — each disappears inside the Anchor after their succession. Someone has cloned the Watcher's credentials and is issuing commands under that identity. Some instructions signed by the Watcher cannot be trusted; a forged closure sequence could accelerate the Convergence instead of stopping it. Dr Assa Abene appears to have anticipated this.",
      fr: "« Watcher » est une fonction, pas une personne — chacun disparaît dans l'Anchor après sa succession. Quelqu'un a cloné les credentials du Watcher et émet des ordres sous cette identité. Certaines instructions signées du Watcher ne sont pas fiables ; une séquence de fermeture falsifiée pourrait accélérer la Convergence au lieu de l'arrêter. Dr Assa Abene semble l'avoir anticipé.",
    },
  },
  {
    key: "architects",
    title: { en: "Reality as Software", fr: "La réalité comme logiciel" },
    triggers: ["F-28", "F-04", "F-26"], threshold: 2,
    entities: ["architects"],
    lockLabel: { en: "NON-HUMAN PATTERN UNRESOLVED", fr: "MOTIF NON HUMAIN NON RÉSOLU" },
    reveal: {
      en: "The Anchor's oldest systems answer to no human architecture. The unidentified designation found inside them — the Architects — did not program machines: they treated relationships between realities as something that could be executed. The Digital Gates are not natural phenomena. Reality itself is being run like software, and the Anchor was already waiting before the monument existed.",
      fr: "Les systèmes les plus anciens de l'Anchor ne répondent à aucune architecture humaine. La désignation non identifiée qu'on y trouve — les Architects — ne programmait pas des machines : elle traitait les relations entre réalités comme quelque chose d'exécutable. Les Digital Gates ne sont pas des phénomènes naturels. La réalité elle-même est exécutée comme un logiciel, et l'Anchor attendait déjà avant que le monument n'existe.",
    },
  },
  {
    key: "final",
    title: { en: "The Seven Seals", fr: "Les sept Sceaux" },
    triggers: ["F-04", "F-15", "F-16", "F-26", "F-30", "F-39", "F-40"], threshold: 7,
    entities: [],
    lockLabel: { en: "SEVEN PRIME SEALS REQUIRED", fr: "SEPT PRIME SEALS REQUIS" },
    reveal: {
      en: "The seven Prime Seals authenticate the Codex itself. Only they can tell the true closure sequence from a forged one — and the sequence signed by the Watcher may not be the true one. Every recovered coordinate converges on a single point beneath Deido. The Codex is not only a map. It is the verification system Dr Assa Abene built for a command chain she knew could be compromised.",
      fr: "Les sept Prime Seals authentifient le Codex lui-même. Eux seuls peuvent distinguer la vraie séquence de fermeture d'une séquence falsifiée — et la séquence signée par le Watcher n'est peut-être pas la vraie. Chaque coordonnée récupérée converge vers un seul point sous Deido. Le Codex n'est pas qu'une carte. C'est le système de vérification que Dr Assa Abene a conçu pour une chaîne de commandement qu'elle savait compromissible.",
    },
  },
];

/** Which arc (if any) declassifies a given entity dossier. */
export function arcForEntity(entityKey: string): Arc | undefined {
  return ARCS.find((a) => a.entities.includes(entityKey));
}

// Per-entity image redaction level at launch (design analysis §9): visible cards
// (only the deeper dossier truth is gated), partially masked, or heavily masked.
// Heavy/partial cards un-blur when their arc declassifies.
export const ENTITY_BLUR: Record<string, "none" | "partial" | "heavy"> = {
  assa: "none", voss: "none", nora: "none", protocol: "none", meridian: "none",
  samuel: "partial", directorate: "partial",
  watcher: "heavy", nullchoir: "heavy", architects: "heavy",
};
