CREATE TABLE `testimonies` (
  `id`        INT NOT NULL AUTO_INCREMENT,
  `quoteEn`   LONGTEXT NOT NULL,
  `quoteFr`   LONGTEXT NULL,
  `author`    VARCHAR(191) NOT NULL,
  `isVisible` BOOLEAN NOT NULL DEFAULT true,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
