CREATE TABLE `logistics_prospects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sector` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `contact_name` VARCHAR(191) NULL,
  `contact_title` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `phone` VARCHAR(191) NULL,
  `website` VARCHAR(191) NULL,
  `address` VARCHAR(191) NULL,
  `city` VARCHAR(191) NOT NULL DEFAULT 'Douala',
  `google_place_id` VARCHAR(191) NULL,
  `google_rating` DOUBLE NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'new',
  `notes` LONGTEXT NULL,
  `ai_draft_email_fr` LONGTEXT NULL,
  `ai_draft_email_en` LONGTEXT NULL,
  `last_contact_at` DATETIME(3) NULL,
  `source` VARCHAR(191) NOT NULL DEFAULT 'manual',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  UNIQUE INDEX `logistics_prospects_google_place_id_key`(`google_place_id`),
  INDEX `logistics_prospects_sector_idx`(`sector`),
  INDEX `logistics_prospects_status_idx`(`status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
