ALTER TABLE `cfp_submissions`
  ADD COLUMN IF NOT EXISTS `linkedin` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `twitter`  VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `whatsapp` VARCHAR(191) NULL;

ALTER TABLE `volunteer_applications`
  ADD COLUMN IF NOT EXISTS `linkedin`      VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `twitter`       VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `whatsapp`      VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `hoursPerWeek`  VARCHAR(191) NULL;
